// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/pure-golang/budva-claude/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewAlbumService creates a new instance of AlbumService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlbumService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlbumService {
	mock := &AlbumService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AlbumService is an autogenerated mock type for the albumService type
type AlbumService struct {
	mock.Mock
}

type AlbumService_Expecter struct {
	mock *mock.Mock
}

func (_m *AlbumService) EXPECT() *AlbumService_Expecter {
	return &AlbumService_Expecter{mock: &_m.Mock}
}

// AddMessage provides a mock function for the type AlbumService
func (_mock *AlbumService) AddMessage(key domain.MediaAlbumKey, msg *domain.Message) bool {
	ret := _mock.Called(key, msg)

	if len(ret) == 0 {
		panic("no return value specified for AddMessage")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(domain.MediaAlbumKey, *domain.Message) bool); ok {
		r0 = returnFunc(key, msg)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// AlbumService_AddMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMessage'
type AlbumService_AddMessage_Call struct {
	*mock.Call
}

// AddMessage is a helper method to define mock.On call
//   - key domain.MediaAlbumKey
//   - msg *domain.Message
func (_e *AlbumService_Expecter) AddMessage(key interface{}, msg interface{}) *AlbumService_AddMessage_Call {
	return &AlbumService_AddMessage_Call{Call: _e.mock.On("AddMessage", key, msg)}
}

func (_c *AlbumService_AddMessage_Call) Run(run func(key domain.MediaAlbumKey, msg *domain.Message)) *AlbumService_AddMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.MediaAlbumKey
		if args[0] != nil {
			arg0 = args[0].(domain.MediaAlbumKey)
		}
		var arg1 *domain.Message
		if args[1] != nil {
			arg1 = args[1].(*domain.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AlbumService_AddMessage_Call) Return(b bool) *AlbumService_AddMessage_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *AlbumService_AddMessage_Call) RunAndReturn(run func(key domain.MediaAlbumKey, msg *domain.Message) bool) *AlbumService_AddMessage_Call {
	_c.Call.Return(run)
	return _c
}

// LastReceivedAge provides a mock function for the type AlbumService
func (_mock *AlbumService) LastReceivedAge(key domain.MediaAlbumKey) time.Duration {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for LastReceivedAge")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(domain.MediaAlbumKey) time.Duration); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// AlbumService_LastReceivedAge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastReceivedAge'
type AlbumService_LastReceivedAge_Call struct {
	*mock.Call
}

// LastReceivedAge is a helper method to define mock.On call
//   - key domain.MediaAlbumKey
func (_e *AlbumService_Expecter) LastReceivedAge(key interface{}) *AlbumService_LastReceivedAge_Call {
	return &AlbumService_LastReceivedAge_Call{Call: _e.mock.On("LastReceivedAge", key)}
}

func (_c *AlbumService_LastReceivedAge_Call) Run(run func(key domain.MediaAlbumKey)) *AlbumService_LastReceivedAge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.MediaAlbumKey
		if args[0] != nil {
			arg0 = args[0].(domain.MediaAlbumKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AlbumService_LastReceivedAge_Call) Return(duration time.Duration) *AlbumService_LastReceivedAge_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *AlbumService_LastReceivedAge_Call) RunAndReturn(run func(key domain.MediaAlbumKey) time.Duration) *AlbumService_LastReceivedAge_Call {
	_c.Call.Return(run)
	return _c
}

// PopMessages provides a mock function for the type AlbumService
func (_mock *AlbumService) PopMessages(key domain.MediaAlbumKey) []*domain.Message {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for PopMessages")
	}

	var r0 []*domain.Message
	if returnFunc, ok := ret.Get(0).(func(domain.MediaAlbumKey) []*domain.Message); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}
	return r0
}

// AlbumService_PopMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PopMessages'
type AlbumService_PopMessages_Call struct {
	*mock.Call
}

// PopMessages is a helper method to define mock.On call
//   - key domain.MediaAlbumKey
func (_e *AlbumService_Expecter) PopMessages(key interface{}) *AlbumService_PopMessages_Call {
	return &AlbumService_PopMessages_Call{Call: _e.mock.On("PopMessages", key)}
}

func (_c *AlbumService_PopMessages_Call) Run(run func(key domain.MediaAlbumKey)) *AlbumService_PopMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.MediaAlbumKey
		if args[0] != nil {
			arg0 = args[0].(domain.MediaAlbumKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AlbumService_PopMessages_Call) Return(messages []*domain.Message) *AlbumService_PopMessages_Call {
	_c.Call.Return(messages)
	return _c
}

func (_c *AlbumService_PopMessages_Call) RunAndReturn(run func(key domain.MediaAlbumKey) []*domain.Message) *AlbumService_PopMessages_Call {
	_c.Call.Return(run)
	return _c
}
