// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/pure-golang/budva-claude/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewDedupTracker creates a new instance of DedupTracker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDedupTracker(t interface {
	mock.TestingT
	Cleanup(func())
}) *DedupTracker {
	mock := &DedupTracker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DedupTracker is an autogenerated mock type for the DedupTracker type
type DedupTracker struct {
	mock.Mock
}

type DedupTracker_Expecter struct {
	mock *mock.Mock
}

func (_m *DedupTracker) EXPECT() *DedupTracker_Expecter {
	return &DedupTracker_Expecter{mock: &_m.Mock}
}

// TryMark provides a mock function for the type DedupTracker
func (_mock *DedupTracker) TryMark(chatID domain.ChatID) bool {
	ret := _mock.Called(chatID)

	if len(ret) == 0 {
		panic("no return value specified for TryMark")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID) bool); ok {
		r0 = returnFunc(chatID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// DedupTracker_TryMark_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryMark'
type DedupTracker_TryMark_Call struct {
	*mock.Call
}

// TryMark is a helper method to define mock.On call
//   - chatID domain.ChatID
func (_e *DedupTracker_Expecter) TryMark(chatID interface{}) *DedupTracker_TryMark_Call {
	return &DedupTracker_TryMark_Call{Call: _e.mock.On("TryMark", chatID)}
}

func (_c *DedupTracker_TryMark_Call) Run(run func(chatID domain.ChatID)) *DedupTracker_TryMark_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DedupTracker_TryMark_Call) Return(b bool) *DedupTracker_TryMark_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *DedupTracker_TryMark_Call) RunAndReturn(run func(chatID domain.ChatID) bool) *DedupTracker_TryMark_Call {
	_c.Call.Return(run)
	return _c
}
