// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/pure-golang/budva-claude/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TransformService is an autogenerated mock type for the transformService type
type TransformService struct {
	mock.Mock
}

type TransformService_Expecter struct {
	mock *mock.Mock
}

func (_m *TransformService) EXPECT() *TransformService_Expecter {
	return &TransformService_Expecter{mock: &_m.Mock}
}

// AddNextLink provides a mock function with given fields: ctx, text, src, dstChatID, nextMessageID
func (_m *TransformService) AddNextLink(ctx context.Context, text *domain.FormattedText, src *domain.Source, dstChatID int64, nextMessageID int64) *domain.FormattedText {
	ret := _m.Called(ctx, text, src, dstChatID, nextMessageID)

	if len(ret) == 0 {
		panic("no return value specified for AddNextLink")
	}

	var r0 *domain.FormattedText
	if rf, ok := ret.Get(0).(func(context.Context, *domain.FormattedText, *domain.Source, int64, int64) *domain.FormattedText); ok {
		r0 = rf(ctx, text, src, dstChatID, nextMessageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FormattedText)
		}
	}

	return r0
}

// TransformService_AddNextLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNextLink'
type TransformService_AddNextLink_Call struct {
	*mock.Call
}

// AddNextLink is a helper method to define mock.On call
//   - ctx context.Context
//   - text *domain.FormattedText
//   - src *domain.Source
//   - dstChatID int64
//   - nextMessageID int64
func (_e *TransformService_Expecter) AddNextLink(ctx interface{}, text interface{}, src interface{}, dstChatID interface{}, nextMessageID interface{}) *TransformService_AddNextLink_Call {
	return &TransformService_AddNextLink_Call{Call: _e.mock.On("AddNextLink", ctx, text, src, dstChatID, nextMessageID)}
}

func (_c *TransformService_AddNextLink_Call) Run(run func(ctx context.Context, text *domain.FormattedText, src *domain.Source, dstChatID int64, nextMessageID int64)) *TransformService_AddNextLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.FormattedText), args[2].(*domain.Source), args[3].(int64), args[4].(int64))
	})
	return _c
}

func (_c *TransformService_AddNextLink_Call) Return(_a0 *domain.FormattedText) *TransformService_AddNextLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransformService_AddNextLink_Call) RunAndReturn(run func(context.Context, *domain.FormattedText, *domain.Source, int64, int64) *domain.FormattedText) *TransformService_AddNextLink_Call {
	_c.Call.Return(run)
	return _c
}

// Transform provides a mock function with given fields: ctx, params
func (_m *TransformService) Transform(ctx context.Context, params domain.TransformParams) (*domain.FormattedText, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Transform")
	}

	var r0 *domain.FormattedText
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TransformParams) (*domain.FormattedText, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TransformParams) *domain.FormattedText); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FormattedText)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TransformParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransformService_Transform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transform'
type TransformService_Transform_Call struct {
	*mock.Call
}

// Transform is a helper method to define mock.On call
//   - ctx context.Context
//   - params domain.TransformParams
func (_e *TransformService_Expecter) Transform(ctx interface{}, params interface{}) *TransformService_Transform_Call {
	return &TransformService_Transform_Call{Call: _e.mock.On("Transform", ctx, params)}
}

func (_c *TransformService_Transform_Call) Run(run func(ctx context.Context, params domain.TransformParams)) *TransformService_Transform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TransformParams))
	})
	return _c
}

func (_c *TransformService_Transform_Call) Return(_a0 *domain.FormattedText, _a1 error) *TransformService_Transform_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransformService_Transform_Call) RunAndReturn(run func(context.Context, domain.TransformParams) (*domain.FormattedText, error)) *TransformService_Transform_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransformService creates a new instance of TransformService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransformService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransformService {
	mock := &TransformService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
