// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "github.com/pure-golang/budva-claude/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MessageService is an autogenerated mock type for the messageService type
type MessageService struct {
	mock.Mock
}

type MessageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageService) EXPECT() *MessageService_Expecter {
	return &MessageService_Expecter{mock: &_m.Mock}
}

// BuildInputContent provides a mock function with given fields: msg, text
func (_m *MessageService) BuildInputContent(msg *domain.Message, text *domain.FormattedText) domain.InputMessageContent {
	ret := _m.Called(msg, text)

	if len(ret) == 0 {
		panic("no return value specified for BuildInputContent")
	}

	var r0 domain.InputMessageContent
	if rf, ok := ret.Get(0).(func(*domain.Message, *domain.FormattedText) domain.InputMessageContent); ok {
		r0 = rf(msg, text)
	} else {
		r0 = ret.Get(0).(domain.InputMessageContent)
	}

	return r0
}

// MessageService_BuildInputContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildInputContent'
type MessageService_BuildInputContent_Call struct {
	*mock.Call
}

// BuildInputContent is a helper method to define mock.On call
//   - msg *domain.Message
//   - text *domain.FormattedText
func (_e *MessageService_Expecter) BuildInputContent(msg interface{}, text interface{}) *MessageService_BuildInputContent_Call {
	return &MessageService_BuildInputContent_Call{Call: _e.mock.On("BuildInputContent", msg, text)}
}

func (_c *MessageService_BuildInputContent_Call) Run(run func(msg *domain.Message, text *domain.FormattedText)) *MessageService_BuildInputContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Message), args[1].(*domain.FormattedText))
	})
	return _c
}

func (_c *MessageService_BuildInputContent_Call) Return(_a0 domain.InputMessageContent) *MessageService_BuildInputContent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageService_BuildInputContent_Call) RunAndReturn(run func(*domain.Message, *domain.FormattedText) domain.InputMessageContent) *MessageService_BuildInputContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormattedText provides a mock function with given fields: msg
func (_m *MessageService) GetFormattedText(msg *domain.Message) *domain.FormattedText {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for GetFormattedText")
	}

	var r0 *domain.FormattedText
	if rf, ok := ret.Get(0).(func(*domain.Message) *domain.FormattedText); ok {
		r0 = rf(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FormattedText)
		}
	}

	return r0
}

// MessageService_GetFormattedText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormattedText'
type MessageService_GetFormattedText_Call struct {
	*mock.Call
}

// GetFormattedText is a helper method to define mock.On call
//   - msg *domain.Message
func (_e *MessageService_Expecter) GetFormattedText(msg interface{}) *MessageService_GetFormattedText_Call {
	return &MessageService_GetFormattedText_Call{Call: _e.mock.On("GetFormattedText", msg)}
}

func (_c *MessageService_GetFormattedText_Call) Run(run func(msg *domain.Message)) *MessageService_GetFormattedText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Message))
	})
	return _c
}

func (_c *MessageService_GetFormattedText_Call) Return(_a0 *domain.FormattedText) *MessageService_GetFormattedText_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageService_GetFormattedText_Call) RunAndReturn(run func(*domain.Message) *domain.FormattedText) *MessageService_GetFormattedText_Call {
	_c.Call.Return(run)
	return _c
}

// GetReplyMarkupData provides a mock function with given fields: msg
func (_m *MessageService) GetReplyMarkupData(msg *domain.Message) []byte {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for GetReplyMarkupData")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func(*domain.Message) []byte); ok {
		r0 = rf(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// MessageService_GetReplyMarkupData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReplyMarkupData'
type MessageService_GetReplyMarkupData_Call struct {
	*mock.Call
}

// GetReplyMarkupData is a helper method to define mock.On call
//   - msg *domain.Message
func (_e *MessageService_Expecter) GetReplyMarkupData(msg interface{}) *MessageService_GetReplyMarkupData_Call {
	return &MessageService_GetReplyMarkupData_Call{Call: _e.mock.On("GetReplyMarkupData", msg)}
}

func (_c *MessageService_GetReplyMarkupData_Call) Run(run func(msg *domain.Message)) *MessageService_GetReplyMarkupData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Message))
	})
	return _c
}

func (_c *MessageService_GetReplyMarkupData_Call) Return(_a0 []byte) *MessageService_GetReplyMarkupData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageService_GetReplyMarkupData_Call) RunAndReturn(run func(*domain.Message) []byte) *MessageService_GetReplyMarkupData_Call {
	_c.Call.Return(run)
	return _c
}

// IsSystemMessage provides a mock function with given fields: msg
func (_m *MessageService) IsSystemMessage(msg *domain.Message) bool {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for IsSystemMessage")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*domain.Message) bool); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MessageService_IsSystemMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSystemMessage'
type MessageService_IsSystemMessage_Call struct {
	*mock.Call
}

// IsSystemMessage is a helper method to define mock.On call
//   - msg *domain.Message
func (_e *MessageService_Expecter) IsSystemMessage(msg interface{}) *MessageService_IsSystemMessage_Call {
	return &MessageService_IsSystemMessage_Call{Call: _e.mock.On("IsSystemMessage", msg)}
}

func (_c *MessageService_IsSystemMessage_Call) Run(run func(msg *domain.Message)) *MessageService_IsSystemMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Message))
	})
	return _c
}

func (_c *MessageService_IsSystemMessage_Call) Return(_a0 bool) *MessageService_IsSystemMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageService_IsSystemMessage_Call) RunAndReturn(run func(*domain.Message) bool) *MessageService_IsSystemMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageService creates a new instance of MessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageService {
	mock := &MessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
