// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// AlbumService is an autogenerated mock type for the albumService type
type AlbumService struct {
	mock.Mock
}

type AlbumService_Expecter struct {
	mock *mock.Mock
}

func (_m *AlbumService) EXPECT() *AlbumService_Expecter {
	return &AlbumService_Expecter{mock: &_m.Mock}
}

// AddMessage provides a mock function with given fields: key, messageID
func (_m *AlbumService) AddMessage(key string, messageID int64) bool {
	ret := _m.Called(key, messageID)

	if len(ret) == 0 {
		panic("no return value specified for AddMessage")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, int64) bool); ok {
		r0 = rf(key, messageID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// AlbumService_AddMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMessage'
type AlbumService_AddMessage_Call struct {
	*mock.Call
}

// AddMessage is a helper method to define mock.On call
//   - key string
//   - messageID int64
func (_e *AlbumService_Expecter) AddMessage(key interface{}, messageID interface{}) *AlbumService_AddMessage_Call {
	return &AlbumService_AddMessage_Call{Call: _e.mock.On("AddMessage", key, messageID)}
}

func (_c *AlbumService_AddMessage_Call) Run(run func(key string, messageID int64)) *AlbumService_AddMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int64))
	})
	return _c
}

func (_c *AlbumService_AddMessage_Call) Return(_a0 bool) *AlbumService_AddMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumService_AddMessage_Call) RunAndReturn(run func(string, int64) bool) *AlbumService_AddMessage_Call {
	_c.Call.Return(run)
	return _c
}

// LastReceivedAge provides a mock function with given fields: key
func (_m *AlbumService) LastReceivedAge(key string) time.Duration {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for LastReceivedAge")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(string) time.Duration); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// AlbumService_LastReceivedAge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastReceivedAge'
type AlbumService_LastReceivedAge_Call struct {
	*mock.Call
}

// LastReceivedAge is a helper method to define mock.On call
//   - key string
func (_e *AlbumService_Expecter) LastReceivedAge(key interface{}) *AlbumService_LastReceivedAge_Call {
	return &AlbumService_LastReceivedAge_Call{Call: _e.mock.On("LastReceivedAge", key)}
}

func (_c *AlbumService_LastReceivedAge_Call) Run(run func(key string)) *AlbumService_LastReceivedAge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AlbumService_LastReceivedAge_Call) Return(_a0 time.Duration) *AlbumService_LastReceivedAge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumService_LastReceivedAge_Call) RunAndReturn(run func(string) time.Duration) *AlbumService_LastReceivedAge_Call {
	_c.Call.Return(run)
	return _c
}

// PopMessages provides a mock function with given fields: key
func (_m *AlbumService) PopMessages(key string) []int64 {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for PopMessages")
	}

	var r0 []int64
	if rf, ok := ret.Get(0).(func(string) []int64); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	return r0
}

// AlbumService_PopMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PopMessages'
type AlbumService_PopMessages_Call struct {
	*mock.Call
}

// PopMessages is a helper method to define mock.On call
//   - key string
func (_e *AlbumService_Expecter) PopMessages(key interface{}) *AlbumService_PopMessages_Call {
	return &AlbumService_PopMessages_Call{Call: _e.mock.On("PopMessages", key)}
}

func (_c *AlbumService_PopMessages_Call) Run(run func(key string)) *AlbumService_PopMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AlbumService_PopMessages_Call) Return(_a0 []int64) *AlbumService_PopMessages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumService_PopMessages_Call) RunAndReturn(run func(string) []int64) *AlbumService_PopMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewAlbumService creates a new instance of AlbumService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlbumService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlbumService {
	mock := &AlbumService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
