// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "github.com/pure-golang/budva-claude/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// FilterService is an autogenerated mock type for the filterService type
type FilterService struct {
	mock.Mock
}

type FilterService_Expecter struct {
	mock *mock.Mock
}

func (_m *FilterService) EXPECT() *FilterService_Expecter {
	return &FilterService_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function with given fields: text, rule
func (_m *FilterService) Evaluate(text string, rule *domain.ForwardRule) string {
	ret := _m.Called(text, rule)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, *domain.ForwardRule) string); ok {
		r0 = rf(text, rule)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// FilterService_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type FilterService_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - text string
//   - rule *domain.ForwardRule
func (_e *FilterService_Expecter) Evaluate(text interface{}, rule interface{}) *FilterService_Evaluate_Call {
	return &FilterService_Evaluate_Call{Call: _e.mock.On("Evaluate", text, rule)}
}

func (_c *FilterService_Evaluate_Call) Run(run func(text string, rule *domain.ForwardRule)) *FilterService_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*domain.ForwardRule))
	})
	return _c
}

func (_c *FilterService_Evaluate_Call) Return(_a0 string) *FilterService_Evaluate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FilterService_Evaluate_Call) RunAndReturn(run func(string, *domain.ForwardRule) string) *FilterService_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}

// NewFilterService creates a new instance of FilterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFilterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FilterService {
	mock := &FilterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
