// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/pure-golang/budva-claude/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TelegramGateway is an autogenerated mock type for the telegramGateway type
type TelegramGateway struct {
	mock.Mock
}

type TelegramGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramGateway) EXPECT() *TelegramGateway_Expecter {
	return &TelegramGateway_Expecter{mock: &_m.Mock}
}

// DeleteMessages provides a mock function with given fields: ctx, chatID, messageIDs, revoke
func (_m *TelegramGateway) DeleteMessages(ctx context.Context, chatID int64, messageIDs []int64, revoke bool) error {
	ret := _m.Called(ctx, chatID, messageIDs, revoke)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []int64, bool) error); ok {
		r0 = rf(ctx, chatID, messageIDs, revoke)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TelegramGateway_DeleteMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessages'
type TelegramGateway_DeleteMessages_Call struct {
	*mock.Call
}

// DeleteMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - messageIDs []int64
//   - revoke bool
func (_e *TelegramGateway_Expecter) DeleteMessages(ctx interface{}, chatID interface{}, messageIDs interface{}, revoke interface{}) *TelegramGateway_DeleteMessages_Call {
	return &TelegramGateway_DeleteMessages_Call{Call: _e.mock.On("DeleteMessages", ctx, chatID, messageIDs, revoke)}
}

func (_c *TelegramGateway_DeleteMessages_Call) Run(run func(ctx context.Context, chatID int64, messageIDs []int64, revoke bool)) *TelegramGateway_DeleteMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]int64), args[3].(bool))
	})
	return _c
}

func (_c *TelegramGateway_DeleteMessages_Call) Return(_a0 error) *TelegramGateway_DeleteMessages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TelegramGateway_DeleteMessages_Call) RunAndReturn(run func(context.Context, int64, []int64, bool) error) *TelegramGateway_DeleteMessages_Call {
	_c.Call.Return(run)
	return _c
}

// EditMessageCaption provides a mock function with given fields: ctx, chatID, messageID, text
func (_m *TelegramGateway) EditMessageCaption(ctx context.Context, chatID int64, messageID int64, text *domain.FormattedText) error {
	ret := _m.Called(ctx, chatID, messageID, text)

	if len(ret) == 0 {
		panic("no return value specified for EditMessageCaption")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, *domain.FormattedText) error); ok {
		r0 = rf(ctx, chatID, messageID, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TelegramGateway_EditMessageCaption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditMessageCaption'
type TelegramGateway_EditMessageCaption_Call struct {
	*mock.Call
}

// EditMessageCaption is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - messageID int64
//   - text *domain.FormattedText
func (_e *TelegramGateway_Expecter) EditMessageCaption(ctx interface{}, chatID interface{}, messageID interface{}, text interface{}) *TelegramGateway_EditMessageCaption_Call {
	return &TelegramGateway_EditMessageCaption_Call{Call: _e.mock.On("EditMessageCaption", ctx, chatID, messageID, text)}
}

func (_c *TelegramGateway_EditMessageCaption_Call) Run(run func(ctx context.Context, chatID int64, messageID int64, text *domain.FormattedText)) *TelegramGateway_EditMessageCaption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(*domain.FormattedText))
	})
	return _c
}

func (_c *TelegramGateway_EditMessageCaption_Call) Return(_a0 error) *TelegramGateway_EditMessageCaption_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TelegramGateway_EditMessageCaption_Call) RunAndReturn(run func(context.Context, int64, int64, *domain.FormattedText) error) *TelegramGateway_EditMessageCaption_Call {
	_c.Call.Return(run)
	return _c
}

// EditMessageText provides a mock function with given fields: ctx, chatID, messageID, text
func (_m *TelegramGateway) EditMessageText(ctx context.Context, chatID int64, messageID int64, text *domain.FormattedText) error {
	ret := _m.Called(ctx, chatID, messageID, text)

	if len(ret) == 0 {
		panic("no return value specified for EditMessageText")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, *domain.FormattedText) error); ok {
		r0 = rf(ctx, chatID, messageID, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TelegramGateway_EditMessageText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditMessageText'
type TelegramGateway_EditMessageText_Call struct {
	*mock.Call
}

// EditMessageText is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - messageID int64
//   - text *domain.FormattedText
func (_e *TelegramGateway_Expecter) EditMessageText(ctx interface{}, chatID interface{}, messageID interface{}, text interface{}) *TelegramGateway_EditMessageText_Call {
	return &TelegramGateway_EditMessageText_Call{Call: _e.mock.On("EditMessageText", ctx, chatID, messageID, text)}
}

func (_c *TelegramGateway_EditMessageText_Call) Run(run func(ctx context.Context, chatID int64, messageID int64, text *domain.FormattedText)) *TelegramGateway_EditMessageText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(*domain.FormattedText))
	})
	return _c
}

func (_c *TelegramGateway_EditMessageText_Call) Return(_a0 error) *TelegramGateway_EditMessageText_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TelegramGateway_EditMessageText_Call) RunAndReturn(run func(context.Context, int64, int64, *domain.FormattedText) error) *TelegramGateway_EditMessageText_Call {
	_c.Call.Return(run)
	return _c
}

// ForwardMessages provides a mock function with given fields: ctx, fromChatID, toChatID, messageIDs
func (_m *TelegramGateway) ForwardMessages(ctx context.Context, fromChatID int64, toChatID int64, messageIDs []int64) ([]int64, error) {
	ret := _m.Called(ctx, fromChatID, toChatID, messageIDs)

	if len(ret) == 0 {
		panic("no return value specified for ForwardMessages")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, []int64) ([]int64, error)); ok {
		return rf(ctx, fromChatID, toChatID, messageIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, []int64) []int64); ok {
		r0 = rf(ctx, fromChatID, toChatID, messageIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, []int64) error); ok {
		r1 = rf(ctx, fromChatID, toChatID, messageIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TelegramGateway_ForwardMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForwardMessages'
type TelegramGateway_ForwardMessages_Call struct {
	*mock.Call
}

// ForwardMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - fromChatID int64
//   - toChatID int64
//   - messageIDs []int64
func (_e *TelegramGateway_Expecter) ForwardMessages(ctx interface{}, fromChatID interface{}, toChatID interface{}, messageIDs interface{}) *TelegramGateway_ForwardMessages_Call {
	return &TelegramGateway_ForwardMessages_Call{Call: _e.mock.On("ForwardMessages", ctx, fromChatID, toChatID, messageIDs)}
}

func (_c *TelegramGateway_ForwardMessages_Call) Run(run func(ctx context.Context, fromChatID int64, toChatID int64, messageIDs []int64)) *TelegramGateway_ForwardMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].([]int64))
	})
	return _c
}

func (_c *TelegramGateway_ForwardMessages_Call) Return(_a0 []int64, _a1 error) *TelegramGateway_ForwardMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TelegramGateway_ForwardMessages_Call) RunAndReturn(run func(context.Context, int64, int64, []int64) ([]int64, error)) *TelegramGateway_ForwardMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessage provides a mock function with given fields: ctx, chatID, messageID
func (_m *TelegramGateway) GetMessage(ctx context.Context, chatID int64, messageID int64) (*domain.Message, error) {
	ret := _m.Called(ctx, chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*domain.Message, error)); ok {
		return rf(ctx, chatID, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *domain.Message); ok {
		r0 = rf(ctx, chatID, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, chatID, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TelegramGateway_GetMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessage'
type TelegramGateway_GetMessage_Call struct {
	*mock.Call
}

// GetMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - messageID int64
func (_e *TelegramGateway_Expecter) GetMessage(ctx interface{}, chatID interface{}, messageID interface{}) *TelegramGateway_GetMessage_Call {
	return &TelegramGateway_GetMessage_Call{Call: _e.mock.On("GetMessage", ctx, chatID, messageID)}
}

func (_c *TelegramGateway_GetMessage_Call) Run(run func(ctx context.Context, chatID int64, messageID int64)) *TelegramGateway_GetMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *TelegramGateway_GetMessage_Call) Return(_a0 *domain.Message, _a1 error) *TelegramGateway_GetMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TelegramGateway_GetMessage_Call) RunAndReturn(run func(context.Context, int64, int64) (*domain.Message, error)) *TelegramGateway_GetMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageLink provides a mock function with given fields: ctx, chatID, messageID
func (_m *TelegramGateway) GetMessageLink(ctx context.Context, chatID int64, messageID int64) (string, error) {
	ret := _m.Called(ctx, chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (string, error)); ok {
		return rf(ctx, chatID, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) string); ok {
		r0 = rf(ctx, chatID, messageID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, chatID, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TelegramGateway_GetMessageLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageLink'
type TelegramGateway_GetMessageLink_Call struct {
	*mock.Call
}

// GetMessageLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - messageID int64
func (_e *TelegramGateway_Expecter) GetMessageLink(ctx interface{}, chatID interface{}, messageID interface{}) *TelegramGateway_GetMessageLink_Call {
	return &TelegramGateway_GetMessageLink_Call{Call: _e.mock.On("GetMessageLink", ctx, chatID, messageID)}
}

func (_c *TelegramGateway_GetMessageLink_Call) Run(run func(ctx context.Context, chatID int64, messageID int64)) *TelegramGateway_GetMessageLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *TelegramGateway_GetMessageLink_Call) Return(_a0 string, _a1 error) *TelegramGateway_GetMessageLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TelegramGateway_GetMessageLink_Call) RunAndReturn(run func(context.Context, int64, int64) (string, error)) *TelegramGateway_GetMessageLink_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: ctx, chatID, content
func (_m *TelegramGateway) SendMessage(ctx context.Context, chatID int64, content domain.InputMessageContent) (int64, error) {
	ret := _m.Called(ctx, chatID, content)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.InputMessageContent) (int64, error)); ok {
		return rf(ctx, chatID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.InputMessageContent) int64); ok {
		r0 = rf(ctx, chatID, content)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.InputMessageContent) error); ok {
		r1 = rf(ctx, chatID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TelegramGateway_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type TelegramGateway_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - content domain.InputMessageContent
func (_e *TelegramGateway_Expecter) SendMessage(ctx interface{}, chatID interface{}, content interface{}) *TelegramGateway_SendMessage_Call {
	return &TelegramGateway_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, chatID, content)}
}

func (_c *TelegramGateway_SendMessage_Call) Run(run func(ctx context.Context, chatID int64, content domain.InputMessageContent)) *TelegramGateway_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.InputMessageContent))
	})
	return _c
}

func (_c *TelegramGateway_SendMessage_Call) Return(_a0 int64, _a1 error) *TelegramGateway_SendMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TelegramGateway_SendMessage_Call) RunAndReturn(run func(context.Context, int64, domain.InputMessageContent) (int64, error)) *TelegramGateway_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessageAlbum provides a mock function with given fields: ctx, chatID, contents
func (_m *TelegramGateway) SendMessageAlbum(ctx context.Context, chatID int64, contents []domain.InputMessageContent) ([]int64, error) {
	ret := _m.Called(ctx, chatID, contents)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageAlbum")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []domain.InputMessageContent) ([]int64, error)); ok {
		return rf(ctx, chatID, contents)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, []domain.InputMessageContent) []int64); ok {
		r0 = rf(ctx, chatID, contents)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, []domain.InputMessageContent) error); ok {
		r1 = rf(ctx, chatID, contents)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TelegramGateway_SendMessageAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageAlbum'
type TelegramGateway_SendMessageAlbum_Call struct {
	*mock.Call
}

// SendMessageAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - contents []domain.InputMessageContent
func (_e *TelegramGateway_Expecter) SendMessageAlbum(ctx interface{}, chatID interface{}, contents interface{}) *TelegramGateway_SendMessageAlbum_Call {
	return &TelegramGateway_SendMessageAlbum_Call{Call: _e.mock.On("SendMessageAlbum", ctx, chatID, contents)}
}

func (_c *TelegramGateway_SendMessageAlbum_Call) Run(run func(ctx context.Context, chatID int64, contents []domain.InputMessageContent)) *TelegramGateway_SendMessageAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]domain.InputMessageContent))
	})
	return _c
}

func (_c *TelegramGateway_SendMessageAlbum_Call) Return(_a0 []int64, _a1 error) *TelegramGateway_SendMessageAlbum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TelegramGateway_SendMessageAlbum_Call) RunAndReturn(run func(context.Context, int64, []domain.InputMessageContent) ([]int64, error)) *TelegramGateway_SendMessageAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// NewTelegramGateway creates a new instance of TelegramGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramGateway {
	mock := &TelegramGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
