// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StateStore is an autogenerated mock type for the stateStore type
type StateStore struct {
	mock.Mock
}

type StateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *StateStore) EXPECT() *StateStore_Expecter {
	return &StateStore_Expecter{mock: &_m.Mock}
}

// DeleteAnswerMessageID provides a mock function with given fields: dstChatID, tmpMessageID
func (_m *StateStore) DeleteAnswerMessageID(dstChatID int64, tmpMessageID int64) error {
	ret := _m.Called(dstChatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAnswerMessageID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(dstChatID, tmpMessageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateStore_DeleteAnswerMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAnswerMessageID'
type StateStore_DeleteAnswerMessageID_Call struct {
	*mock.Call
}

// DeleteAnswerMessageID is a helper method to define mock.On call
//   - dstChatID int64
//   - tmpMessageID int64
func (_e *StateStore_Expecter) DeleteAnswerMessageID(dstChatID interface{}, tmpMessageID interface{}) *StateStore_DeleteAnswerMessageID_Call {
	return &StateStore_DeleteAnswerMessageID_Call{Call: _e.mock.On("DeleteAnswerMessageID", dstChatID, tmpMessageID)}
}

func (_c *StateStore_DeleteAnswerMessageID_Call) Run(run func(dstChatID int64, tmpMessageID int64)) *StateStore_DeleteAnswerMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *StateStore_DeleteAnswerMessageID_Call) Return(_a0 error) *StateStore_DeleteAnswerMessageID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStore_DeleteAnswerMessageID_Call) RunAndReturn(run func(int64, int64) error) *StateStore_DeleteAnswerMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCopiedMessageIDs provides a mock function with given fields: chatID, messageID
func (_m *StateStore) DeleteCopiedMessageIDs(chatID int64, messageID int64) error {
	ret := _m.Called(chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCopiedMessageIDs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(chatID, messageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateStore_DeleteCopiedMessageIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCopiedMessageIDs'
type StateStore_DeleteCopiedMessageIDs_Call struct {
	*mock.Call
}

// DeleteCopiedMessageIDs is a helper method to define mock.On call
//   - chatID int64
//   - messageID int64
func (_e *StateStore_Expecter) DeleteCopiedMessageIDs(chatID interface{}, messageID interface{}) *StateStore_DeleteCopiedMessageIDs_Call {
	return &StateStore_DeleteCopiedMessageIDs_Call{Call: _e.mock.On("DeleteCopiedMessageIDs", chatID, messageID)}
}

func (_c *StateStore_DeleteCopiedMessageIDs_Call) Run(run func(chatID int64, messageID int64)) *StateStore_DeleteCopiedMessageIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *StateStore_DeleteCopiedMessageIDs_Call) Return(_a0 error) *StateStore_DeleteCopiedMessageIDs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStore_DeleteCopiedMessageIDs_Call) RunAndReturn(run func(int64, int64) error) *StateStore_DeleteCopiedMessageIDs_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNewMessageID provides a mock function with given fields: chatID, tmpMessageID
func (_m *StateStore) DeleteNewMessageID(chatID int64, tmpMessageID int64) error {
	ret := _m.Called(chatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNewMessageID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(chatID, tmpMessageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateStore_DeleteNewMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNewMessageID'
type StateStore_DeleteNewMessageID_Call struct {
	*mock.Call
}

// DeleteNewMessageID is a helper method to define mock.On call
//   - chatID int64
//   - tmpMessageID int64
func (_e *StateStore_Expecter) DeleteNewMessageID(chatID interface{}, tmpMessageID interface{}) *StateStore_DeleteNewMessageID_Call {
	return &StateStore_DeleteNewMessageID_Call{Call: _e.mock.On("DeleteNewMessageID", chatID, tmpMessageID)}
}

func (_c *StateStore_DeleteNewMessageID_Call) Run(run func(chatID int64, tmpMessageID int64)) *StateStore_DeleteNewMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *StateStore_DeleteNewMessageID_Call) Return(_a0 error) *StateStore_DeleteNewMessageID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStore_DeleteNewMessageID_Call) RunAndReturn(run func(int64, int64) error) *StateStore_DeleteNewMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTmpMessageID provides a mock function with given fields: chatID, newMessageID
func (_m *StateStore) DeleteTmpMessageID(chatID int64, newMessageID int64) error {
	ret := _m.Called(chatID, newMessageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTmpMessageID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(chatID, newMessageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateStore_DeleteTmpMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTmpMessageID'
type StateStore_DeleteTmpMessageID_Call struct {
	*mock.Call
}

// DeleteTmpMessageID is a helper method to define mock.On call
//   - chatID int64
//   - newMessageID int64
func (_e *StateStore_Expecter) DeleteTmpMessageID(chatID interface{}, newMessageID interface{}) *StateStore_DeleteTmpMessageID_Call {
	return &StateStore_DeleteTmpMessageID_Call{Call: _e.mock.On("DeleteTmpMessageID", chatID, newMessageID)}
}

func (_c *StateStore_DeleteTmpMessageID_Call) Run(run func(chatID int64, newMessageID int64)) *StateStore_DeleteTmpMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *StateStore_DeleteTmpMessageID_Call) Return(_a0 error) *StateStore_DeleteTmpMessageID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStore_DeleteTmpMessageID_Call) RunAndReturn(run func(int64, int64) error) *StateStore_DeleteTmpMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnswerMessageID provides a mock function with given fields: dstChatID, tmpMessageID
func (_m *StateStore) GetAnswerMessageID(dstChatID int64, tmpMessageID int64) string {
	ret := _m.Called(dstChatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for GetAnswerMessageID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int64, int64) string); ok {
		r0 = rf(dstChatID, tmpMessageID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StateStore_GetAnswerMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnswerMessageID'
type StateStore_GetAnswerMessageID_Call struct {
	*mock.Call
}

// GetAnswerMessageID is a helper method to define mock.On call
//   - dstChatID int64
//   - tmpMessageID int64
func (_e *StateStore_Expecter) GetAnswerMessageID(dstChatID interface{}, tmpMessageID interface{}) *StateStore_GetAnswerMessageID_Call {
	return &StateStore_GetAnswerMessageID_Call{Call: _e.mock.On("GetAnswerMessageID", dstChatID, tmpMessageID)}
}

func (_c *StateStore_GetAnswerMessageID_Call) Run(run func(dstChatID int64, tmpMessageID int64)) *StateStore_GetAnswerMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *StateStore_GetAnswerMessageID_Call) Return(_a0 string) *StateStore_GetAnswerMessageID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStore_GetAnswerMessageID_Call) RunAndReturn(run func(int64, int64) string) *StateStore_GetAnswerMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCopiedMessageIDs provides a mock function with given fields: chatID, messageID
func (_m *StateStore) GetCopiedMessageIDs(chatID int64, messageID int64) []string {
	ret := _m.Called(chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetCopiedMessageIDs")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(int64, int64) []string); ok {
		r0 = rf(chatID, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// StateStore_GetCopiedMessageIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCopiedMessageIDs'
type StateStore_GetCopiedMessageIDs_Call struct {
	*mock.Call
}

// GetCopiedMessageIDs is a helper method to define mock.On call
//   - chatID int64
//   - messageID int64
func (_e *StateStore_Expecter) GetCopiedMessageIDs(chatID interface{}, messageID interface{}) *StateStore_GetCopiedMessageIDs_Call {
	return &StateStore_GetCopiedMessageIDs_Call{Call: _e.mock.On("GetCopiedMessageIDs", chatID, messageID)}
}

func (_c *StateStore_GetCopiedMessageIDs_Call) Run(run func(chatID int64, messageID int64)) *StateStore_GetCopiedMessageIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *StateStore_GetCopiedMessageIDs_Call) Return(_a0 []string) *StateStore_GetCopiedMessageIDs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStore_GetCopiedMessageIDs_Call) RunAndReturn(run func(int64, int64) []string) *StateStore_GetCopiedMessageIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewMessageID provides a mock function with given fields: chatID, tmpMessageID
func (_m *StateStore) GetNewMessageID(chatID int64, tmpMessageID int64) int64 {
	ret := _m.Called(chatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for GetNewMessageID")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(int64, int64) int64); ok {
		r0 = rf(chatID, tmpMessageID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// StateStore_GetNewMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewMessageID'
type StateStore_GetNewMessageID_Call struct {
	*mock.Call
}

// GetNewMessageID is a helper method to define mock.On call
//   - chatID int64
//   - tmpMessageID int64
func (_e *StateStore_Expecter) GetNewMessageID(chatID interface{}, tmpMessageID interface{}) *StateStore_GetNewMessageID_Call {
	return &StateStore_GetNewMessageID_Call{Call: _e.mock.On("GetNewMessageID", chatID, tmpMessageID)}
}

func (_c *StateStore_GetNewMessageID_Call) Run(run func(chatID int64, tmpMessageID int64)) *StateStore_GetNewMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *StateStore_GetNewMessageID_Call) Return(_a0 int64) *StateStore_GetNewMessageID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStore_GetNewMessageID_Call) RunAndReturn(run func(int64, int64) int64) *StateStore_GetNewMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementForwardedMessages provides a mock function with given fields: toChatID, date
func (_m *StateStore) IncrementForwardedMessages(toChatID int64, date string) (uint64, error) {
	ret := _m.Called(toChatID, date)

	if len(ret) == 0 {
		panic("no return value specified for IncrementForwardedMessages")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string) (uint64, error)); ok {
		return rf(toChatID, date)
	}
	if rf, ok := ret.Get(0).(func(int64, string) uint64); ok {
		r0 = rf(toChatID, date)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(toChatID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StateStore_IncrementForwardedMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementForwardedMessages'
type StateStore_IncrementForwardedMessages_Call struct {
	*mock.Call
}

// IncrementForwardedMessages is a helper method to define mock.On call
//   - toChatID int64
//   - date string
func (_e *StateStore_Expecter) IncrementForwardedMessages(toChatID interface{}, date interface{}) *StateStore_IncrementForwardedMessages_Call {
	return &StateStore_IncrementForwardedMessages_Call{Call: _e.mock.On("IncrementForwardedMessages", toChatID, date)}
}

func (_c *StateStore_IncrementForwardedMessages_Call) Run(run func(toChatID int64, date string)) *StateStore_IncrementForwardedMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *StateStore_IncrementForwardedMessages_Call) Return(_a0 uint64, _a1 error) *StateStore_IncrementForwardedMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StateStore_IncrementForwardedMessages_Call) RunAndReturn(run func(int64, string) (uint64, error)) *StateStore_IncrementForwardedMessages_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementViewedMessages provides a mock function with given fields: toChatID, date
func (_m *StateStore) IncrementViewedMessages(toChatID int64, date string) (uint64, error) {
	ret := _m.Called(toChatID, date)

	if len(ret) == 0 {
		panic("no return value specified for IncrementViewedMessages")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string) (uint64, error)); ok {
		return rf(toChatID, date)
	}
	if rf, ok := ret.Get(0).(func(int64, string) uint64); ok {
		r0 = rf(toChatID, date)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(toChatID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StateStore_IncrementViewedMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementViewedMessages'
type StateStore_IncrementViewedMessages_Call struct {
	*mock.Call
}

// IncrementViewedMessages is a helper method to define mock.On call
//   - toChatID int64
//   - date string
func (_e *StateStore_Expecter) IncrementViewedMessages(toChatID interface{}, date interface{}) *StateStore_IncrementViewedMessages_Call {
	return &StateStore_IncrementViewedMessages_Call{Call: _e.mock.On("IncrementViewedMessages", toChatID, date)}
}

func (_c *StateStore_IncrementViewedMessages_Call) Run(run func(toChatID int64, date string)) *StateStore_IncrementViewedMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *StateStore_IncrementViewedMessages_Call) Return(_a0 uint64, _a1 error) *StateStore_IncrementViewedMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StateStore_IncrementViewedMessages_Call) RunAndReturn(run func(int64, string) (uint64, error)) *StateStore_IncrementViewedMessages_Call {
	_c.Call.Return(run)
	return _c
}

// SetAnswerMessageID provides a mock function with given fields: dstChatID, tmpMessageID, srcChatID, srcMessageID
func (_m *StateStore) SetAnswerMessageID(dstChatID int64, tmpMessageID int64, srcChatID int64, srcMessageID int64) error {
	ret := _m.Called(dstChatID, tmpMessageID, srcChatID, srcMessageID)

	if len(ret) == 0 {
		panic("no return value specified for SetAnswerMessageID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64, int64, int64) error); ok {
		r0 = rf(dstChatID, tmpMessageID, srcChatID, srcMessageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateStore_SetAnswerMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAnswerMessageID'
type StateStore_SetAnswerMessageID_Call struct {
	*mock.Call
}

// SetAnswerMessageID is a helper method to define mock.On call
//   - dstChatID int64
//   - tmpMessageID int64
//   - srcChatID int64
//   - srcMessageID int64
func (_e *StateStore_Expecter) SetAnswerMessageID(dstChatID interface{}, tmpMessageID interface{}, srcChatID interface{}, srcMessageID interface{}) *StateStore_SetAnswerMessageID_Call {
	return &StateStore_SetAnswerMessageID_Call{Call: _e.mock.On("SetAnswerMessageID", dstChatID, tmpMessageID, srcChatID, srcMessageID)}
}

func (_c *StateStore_SetAnswerMessageID_Call) Run(run func(dstChatID int64, tmpMessageID int64, srcChatID int64, srcMessageID int64)) *StateStore_SetAnswerMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *StateStore_SetAnswerMessageID_Call) Return(_a0 error) *StateStore_SetAnswerMessageID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStore_SetAnswerMessageID_Call) RunAndReturn(run func(int64, int64, int64, int64) error) *StateStore_SetAnswerMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// SetCopiedMessageID provides a mock function with given fields: chatID, messageID, toChatMessageID
func (_m *StateStore) SetCopiedMessageID(chatID int64, messageID int64, toChatMessageID string) error {
	ret := _m.Called(chatID, messageID, toChatMessageID)

	if len(ret) == 0 {
		panic("no return value specified for SetCopiedMessageID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64, string) error); ok {
		r0 = rf(chatID, messageID, toChatMessageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateStore_SetCopiedMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCopiedMessageID'
type StateStore_SetCopiedMessageID_Call struct {
	*mock.Call
}

// SetCopiedMessageID is a helper method to define mock.On call
//   - chatID int64
//   - messageID int64
//   - toChatMessageID string
func (_e *StateStore_Expecter) SetCopiedMessageID(chatID interface{}, messageID interface{}, toChatMessageID interface{}) *StateStore_SetCopiedMessageID_Call {
	return &StateStore_SetCopiedMessageID_Call{Call: _e.mock.On("SetCopiedMessageID", chatID, messageID, toChatMessageID)}
}

func (_c *StateStore_SetCopiedMessageID_Call) Run(run func(chatID int64, messageID int64, toChatMessageID string)) *StateStore_SetCopiedMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *StateStore_SetCopiedMessageID_Call) Return(_a0 error) *StateStore_SetCopiedMessageID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStore_SetCopiedMessageID_Call) RunAndReturn(run func(int64, int64, string) error) *StateStore_SetCopiedMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// SetNewMessageID provides a mock function with given fields: chatID, tmpMessageID, newMessageID
func (_m *StateStore) SetNewMessageID(chatID int64, tmpMessageID int64, newMessageID int64) error {
	ret := _m.Called(chatID, tmpMessageID, newMessageID)

	if len(ret) == 0 {
		panic("no return value specified for SetNewMessageID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64, int64) error); ok {
		r0 = rf(chatID, tmpMessageID, newMessageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateStore_SetNewMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNewMessageID'
type StateStore_SetNewMessageID_Call struct {
	*mock.Call
}

// SetNewMessageID is a helper method to define mock.On call
//   - chatID int64
//   - tmpMessageID int64
//   - newMessageID int64
func (_e *StateStore_Expecter) SetNewMessageID(chatID interface{}, tmpMessageID interface{}, newMessageID interface{}) *StateStore_SetNewMessageID_Call {
	return &StateStore_SetNewMessageID_Call{Call: _e.mock.On("SetNewMessageID", chatID, tmpMessageID, newMessageID)}
}

func (_c *StateStore_SetNewMessageID_Call) Run(run func(chatID int64, tmpMessageID int64, newMessageID int64)) *StateStore_SetNewMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *StateStore_SetNewMessageID_Call) Return(_a0 error) *StateStore_SetNewMessageID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStore_SetNewMessageID_Call) RunAndReturn(run func(int64, int64, int64) error) *StateStore_SetNewMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// SetTmpMessageID provides a mock function with given fields: chatID, newMessageID, tmpMessageID
func (_m *StateStore) SetTmpMessageID(chatID int64, newMessageID int64, tmpMessageID int64) error {
	ret := _m.Called(chatID, newMessageID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for SetTmpMessageID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64, int64) error); ok {
		r0 = rf(chatID, newMessageID, tmpMessageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateStore_SetTmpMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTmpMessageID'
type StateStore_SetTmpMessageID_Call struct {
	*mock.Call
}

// SetTmpMessageID is a helper method to define mock.On call
//   - chatID int64
//   - newMessageID int64
//   - tmpMessageID int64
func (_e *StateStore_Expecter) SetTmpMessageID(chatID interface{}, newMessageID interface{}, tmpMessageID interface{}) *StateStore_SetTmpMessageID_Call {
	return &StateStore_SetTmpMessageID_Call{Call: _e.mock.On("SetTmpMessageID", chatID, newMessageID, tmpMessageID)}
}

func (_c *StateStore_SetTmpMessageID_Call) Run(run func(chatID int64, newMessageID int64, tmpMessageID int64)) *StateStore_SetTmpMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *StateStore_SetTmpMessageID_Call) Return(_a0 error) *StateStore_SetTmpMessageID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStore_SetTmpMessageID_Call) RunAndReturn(run func(int64, int64, int64) error) *StateStore_SetTmpMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// NewStateStore creates a new instance of StateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateStore {
	mock := &StateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
