// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewRateLimiter creates a new instance of RateLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRateLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *RateLimiter {
	mock := &RateLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RateLimiter is an autogenerated mock type for the rateLimiter type
type RateLimiter struct {
	mock.Mock
}

type RateLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *RateLimiter) EXPECT() *RateLimiter_Expecter {
	return &RateLimiter_Expecter{mock: &_m.Mock}
}

// WaitForForward provides a mock function for the type RateLimiter
func (_mock *RateLimiter) WaitForForward(ctx context.Context, dstChatID int64) {
	_mock.Called(ctx, dstChatID)
	return
}

// RateLimiter_WaitForForward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForForward'
type RateLimiter_WaitForForward_Call struct {
	*mock.Call
}

// WaitForForward is a helper method to define mock.On call
//   - ctx context.Context
//   - dstChatID int64
func (_e *RateLimiter_Expecter) WaitForForward(ctx interface{}, dstChatID interface{}) *RateLimiter_WaitForForward_Call {
	return &RateLimiter_WaitForForward_Call{Call: _e.mock.On("WaitForForward", ctx, dstChatID)}
}

func (_c *RateLimiter_WaitForForward_Call) Run(run func(ctx context.Context, dstChatID int64)) *RateLimiter_WaitForForward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RateLimiter_WaitForForward_Call) Return() *RateLimiter_WaitForForward_Call {
	_c.Call.Return()
	return _c
}

func (_c *RateLimiter_WaitForForward_Call) RunAndReturn(run func(ctx context.Context, dstChatID int64)) *RateLimiter_WaitForForward_Call {
	_c.Run(run)
	return _c
}
