// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewStateRepo creates a new instance of StateRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateRepo {
	mock := &StateRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StateRepo is an autogenerated mock type for the stateRepo type
type StateRepo struct {
	mock.Mock
}

type StateRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *StateRepo) EXPECT() *StateRepo_Expecter {
	return &StateRepo_Expecter{mock: &_m.Mock}
}

// DeleteAnswerMessageID provides a mock function for the type StateRepo
func (_mock *StateRepo) DeleteAnswerMessageID(dstChatID int64, tmpMessageID int64) error {
	ret := _mock.Called(dstChatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAnswerMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = returnFunc(dstChatID, tmpMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateRepo_DeleteAnswerMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAnswerMessageID'
type StateRepo_DeleteAnswerMessageID_Call struct {
	*mock.Call
}

// DeleteAnswerMessageID is a helper method to define mock.On call
//   - dstChatID int64
//   - tmpMessageID int64
func (_e *StateRepo_Expecter) DeleteAnswerMessageID(dstChatID interface{}, tmpMessageID interface{}) *StateRepo_DeleteAnswerMessageID_Call {
	return &StateRepo_DeleteAnswerMessageID_Call{Call: _e.mock.On("DeleteAnswerMessageID", dstChatID, tmpMessageID)}
}

func (_c *StateRepo_DeleteAnswerMessageID_Call) Run(run func(dstChatID int64, tmpMessageID int64)) *StateRepo_DeleteAnswerMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateRepo_DeleteAnswerMessageID_Call) Return(err error) *StateRepo_DeleteAnswerMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateRepo_DeleteAnswerMessageID_Call) RunAndReturn(run func(dstChatID int64, tmpMessageID int64) error) *StateRepo_DeleteAnswerMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCopiedMessageIDs provides a mock function for the type StateRepo
func (_mock *StateRepo) DeleteCopiedMessageIDs(chatID int64, messageID int64) error {
	ret := _mock.Called(chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCopiedMessageIDs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = returnFunc(chatID, messageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateRepo_DeleteCopiedMessageIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCopiedMessageIDs'
type StateRepo_DeleteCopiedMessageIDs_Call struct {
	*mock.Call
}

// DeleteCopiedMessageIDs is a helper method to define mock.On call
//   - chatID int64
//   - messageID int64
func (_e *StateRepo_Expecter) DeleteCopiedMessageIDs(chatID interface{}, messageID interface{}) *StateRepo_DeleteCopiedMessageIDs_Call {
	return &StateRepo_DeleteCopiedMessageIDs_Call{Call: _e.mock.On("DeleteCopiedMessageIDs", chatID, messageID)}
}

func (_c *StateRepo_DeleteCopiedMessageIDs_Call) Run(run func(chatID int64, messageID int64)) *StateRepo_DeleteCopiedMessageIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateRepo_DeleteCopiedMessageIDs_Call) Return(err error) *StateRepo_DeleteCopiedMessageIDs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateRepo_DeleteCopiedMessageIDs_Call) RunAndReturn(run func(chatID int64, messageID int64) error) *StateRepo_DeleteCopiedMessageIDs_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNewMessageID provides a mock function for the type StateRepo
func (_mock *StateRepo) DeleteNewMessageID(chatID int64, tmpMessageID int64) error {
	ret := _mock.Called(chatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNewMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = returnFunc(chatID, tmpMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateRepo_DeleteNewMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNewMessageID'
type StateRepo_DeleteNewMessageID_Call struct {
	*mock.Call
}

// DeleteNewMessageID is a helper method to define mock.On call
//   - chatID int64
//   - tmpMessageID int64
func (_e *StateRepo_Expecter) DeleteNewMessageID(chatID interface{}, tmpMessageID interface{}) *StateRepo_DeleteNewMessageID_Call {
	return &StateRepo_DeleteNewMessageID_Call{Call: _e.mock.On("DeleteNewMessageID", chatID, tmpMessageID)}
}

func (_c *StateRepo_DeleteNewMessageID_Call) Run(run func(chatID int64, tmpMessageID int64)) *StateRepo_DeleteNewMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateRepo_DeleteNewMessageID_Call) Return(err error) *StateRepo_DeleteNewMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateRepo_DeleteNewMessageID_Call) RunAndReturn(run func(chatID int64, tmpMessageID int64) error) *StateRepo_DeleteNewMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTmpMessageID provides a mock function for the type StateRepo
func (_mock *StateRepo) DeleteTmpMessageID(chatID int64, newMessageID int64) error {
	ret := _mock.Called(chatID, newMessageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTmpMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = returnFunc(chatID, newMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateRepo_DeleteTmpMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTmpMessageID'
type StateRepo_DeleteTmpMessageID_Call struct {
	*mock.Call
}

// DeleteTmpMessageID is a helper method to define mock.On call
//   - chatID int64
//   - newMessageID int64
func (_e *StateRepo_Expecter) DeleteTmpMessageID(chatID interface{}, newMessageID interface{}) *StateRepo_DeleteTmpMessageID_Call {
	return &StateRepo_DeleteTmpMessageID_Call{Call: _e.mock.On("DeleteTmpMessageID", chatID, newMessageID)}
}

func (_c *StateRepo_DeleteTmpMessageID_Call) Run(run func(chatID int64, newMessageID int64)) *StateRepo_DeleteTmpMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateRepo_DeleteTmpMessageID_Call) Return(err error) *StateRepo_DeleteTmpMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateRepo_DeleteTmpMessageID_Call) RunAndReturn(run func(chatID int64, newMessageID int64) error) *StateRepo_DeleteTmpMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnswerMessageID provides a mock function for the type StateRepo
func (_mock *StateRepo) GetAnswerMessageID(dstChatID int64, tmpMessageID int64) string {
	ret := _mock.Called(dstChatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for GetAnswerMessageID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(int64, int64) string); ok {
		r0 = returnFunc(dstChatID, tmpMessageID)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// StateRepo_GetAnswerMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnswerMessageID'
type StateRepo_GetAnswerMessageID_Call struct {
	*mock.Call
}

// GetAnswerMessageID is a helper method to define mock.On call
//   - dstChatID int64
//   - tmpMessageID int64
func (_e *StateRepo_Expecter) GetAnswerMessageID(dstChatID interface{}, tmpMessageID interface{}) *StateRepo_GetAnswerMessageID_Call {
	return &StateRepo_GetAnswerMessageID_Call{Call: _e.mock.On("GetAnswerMessageID", dstChatID, tmpMessageID)}
}

func (_c *StateRepo_GetAnswerMessageID_Call) Run(run func(dstChatID int64, tmpMessageID int64)) *StateRepo_GetAnswerMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateRepo_GetAnswerMessageID_Call) Return(s string) *StateRepo_GetAnswerMessageID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *StateRepo_GetAnswerMessageID_Call) RunAndReturn(run func(dstChatID int64, tmpMessageID int64) string) *StateRepo_GetAnswerMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCopiedMessageIDs provides a mock function for the type StateRepo
func (_mock *StateRepo) GetCopiedMessageIDs(chatID int64, messageID int64) []string {
	ret := _mock.Called(chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetCopiedMessageIDs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(int64, int64) []string); ok {
		r0 = returnFunc(chatID, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// StateRepo_GetCopiedMessageIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCopiedMessageIDs'
type StateRepo_GetCopiedMessageIDs_Call struct {
	*mock.Call
}

// GetCopiedMessageIDs is a helper method to define mock.On call
//   - chatID int64
//   - messageID int64
func (_e *StateRepo_Expecter) GetCopiedMessageIDs(chatID interface{}, messageID interface{}) *StateRepo_GetCopiedMessageIDs_Call {
	return &StateRepo_GetCopiedMessageIDs_Call{Call: _e.mock.On("GetCopiedMessageIDs", chatID, messageID)}
}

func (_c *StateRepo_GetCopiedMessageIDs_Call) Run(run func(chatID int64, messageID int64)) *StateRepo_GetCopiedMessageIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateRepo_GetCopiedMessageIDs_Call) Return(strings []string) *StateRepo_GetCopiedMessageIDs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *StateRepo_GetCopiedMessageIDs_Call) RunAndReturn(run func(chatID int64, messageID int64) []string) *StateRepo_GetCopiedMessageIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewMessageID provides a mock function for the type StateRepo
func (_mock *StateRepo) GetNewMessageID(chatID int64, tmpMessageID int64) int64 {
	ret := _mock.Called(chatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for GetNewMessageID")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(int64, int64) int64); ok {
		r0 = returnFunc(chatID, tmpMessageID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// StateRepo_GetNewMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewMessageID'
type StateRepo_GetNewMessageID_Call struct {
	*mock.Call
}

// GetNewMessageID is a helper method to define mock.On call
//   - chatID int64
//   - tmpMessageID int64
func (_e *StateRepo_Expecter) GetNewMessageID(chatID interface{}, tmpMessageID interface{}) *StateRepo_GetNewMessageID_Call {
	return &StateRepo_GetNewMessageID_Call{Call: _e.mock.On("GetNewMessageID", chatID, tmpMessageID)}
}

func (_c *StateRepo_GetNewMessageID_Call) Run(run func(chatID int64, tmpMessageID int64)) *StateRepo_GetNewMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateRepo_GetNewMessageID_Call) Return(n int64) *StateRepo_GetNewMessageID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *StateRepo_GetNewMessageID_Call) RunAndReturn(run func(chatID int64, tmpMessageID int64) int64) *StateRepo_GetNewMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementForwardedMessages provides a mock function for the type StateRepo
func (_mock *StateRepo) IncrementForwardedMessages(toChatID int64, date string) (uint64, error) {
	ret := _mock.Called(toChatID, date)

	if len(ret) == 0 {
		panic("no return value specified for IncrementForwardedMessages")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, string) (uint64, error)); ok {
		return returnFunc(toChatID, date)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, string) uint64); ok {
		r0 = returnFunc(toChatID, date)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = returnFunc(toChatID, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StateRepo_IncrementForwardedMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementForwardedMessages'
type StateRepo_IncrementForwardedMessages_Call struct {
	*mock.Call
}

// IncrementForwardedMessages is a helper method to define mock.On call
//   - toChatID int64
//   - date string
func (_e *StateRepo_Expecter) IncrementForwardedMessages(toChatID interface{}, date interface{}) *StateRepo_IncrementForwardedMessages_Call {
	return &StateRepo_IncrementForwardedMessages_Call{Call: _e.mock.On("IncrementForwardedMessages", toChatID, date)}
}

func (_c *StateRepo_IncrementForwardedMessages_Call) Run(run func(toChatID int64, date string)) *StateRepo_IncrementForwardedMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateRepo_IncrementForwardedMessages_Call) Return(v uint64, err error) *StateRepo_IncrementForwardedMessages_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *StateRepo_IncrementForwardedMessages_Call) RunAndReturn(run func(toChatID int64, date string) (uint64, error)) *StateRepo_IncrementForwardedMessages_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementViewedMessages provides a mock function for the type StateRepo
func (_mock *StateRepo) IncrementViewedMessages(toChatID int64, date string) (uint64, error) {
	ret := _mock.Called(toChatID, date)

	if len(ret) == 0 {
		panic("no return value specified for IncrementViewedMessages")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, string) (uint64, error)); ok {
		return returnFunc(toChatID, date)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, string) uint64); ok {
		r0 = returnFunc(toChatID, date)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = returnFunc(toChatID, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StateRepo_IncrementViewedMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementViewedMessages'
type StateRepo_IncrementViewedMessages_Call struct {
	*mock.Call
}

// IncrementViewedMessages is a helper method to define mock.On call
//   - toChatID int64
//   - date string
func (_e *StateRepo_Expecter) IncrementViewedMessages(toChatID interface{}, date interface{}) *StateRepo_IncrementViewedMessages_Call {
	return &StateRepo_IncrementViewedMessages_Call{Call: _e.mock.On("IncrementViewedMessages", toChatID, date)}
}

func (_c *StateRepo_IncrementViewedMessages_Call) Run(run func(toChatID int64, date string)) *StateRepo_IncrementViewedMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateRepo_IncrementViewedMessages_Call) Return(v uint64, err error) *StateRepo_IncrementViewedMessages_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *StateRepo_IncrementViewedMessages_Call) RunAndReturn(run func(toChatID int64, date string) (uint64, error)) *StateRepo_IncrementViewedMessages_Call {
	_c.Call.Return(run)
	return _c
}

// SetAnswerMessageID provides a mock function for the type StateRepo
func (_mock *StateRepo) SetAnswerMessageID(dstChatID int64, tmpMessageID int64, srcChatID int64, srcMessageID int64) error {
	ret := _mock.Called(dstChatID, tmpMessageID, srcChatID, srcMessageID)

	if len(ret) == 0 {
		panic("no return value specified for SetAnswerMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64, int64, int64) error); ok {
		r0 = returnFunc(dstChatID, tmpMessageID, srcChatID, srcMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateRepo_SetAnswerMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAnswerMessageID'
type StateRepo_SetAnswerMessageID_Call struct {
	*mock.Call
}

// SetAnswerMessageID is a helper method to define mock.On call
//   - dstChatID int64
//   - tmpMessageID int64
//   - srcChatID int64
//   - srcMessageID int64
func (_e *StateRepo_Expecter) SetAnswerMessageID(dstChatID interface{}, tmpMessageID interface{}, srcChatID interface{}, srcMessageID interface{}) *StateRepo_SetAnswerMessageID_Call {
	return &StateRepo_SetAnswerMessageID_Call{Call: _e.mock.On("SetAnswerMessageID", dstChatID, tmpMessageID, srcChatID, srcMessageID)}
}

func (_c *StateRepo_SetAnswerMessageID_Call) Run(run func(dstChatID int64, tmpMessageID int64, srcChatID int64, srcMessageID int64)) *StateRepo_SetAnswerMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *StateRepo_SetAnswerMessageID_Call) Return(err error) *StateRepo_SetAnswerMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateRepo_SetAnswerMessageID_Call) RunAndReturn(run func(dstChatID int64, tmpMessageID int64, srcChatID int64, srcMessageID int64) error) *StateRepo_SetAnswerMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// SetCopiedMessageID provides a mock function for the type StateRepo
func (_mock *StateRepo) SetCopiedMessageID(chatID int64, messageID int64, toChatMessageID string) error {
	ret := _mock.Called(chatID, messageID, toChatMessageID)

	if len(ret) == 0 {
		panic("no return value specified for SetCopiedMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64, string) error); ok {
		r0 = returnFunc(chatID, messageID, toChatMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateRepo_SetCopiedMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCopiedMessageID'
type StateRepo_SetCopiedMessageID_Call struct {
	*mock.Call
}

// SetCopiedMessageID is a helper method to define mock.On call
//   - chatID int64
//   - messageID int64
//   - toChatMessageID string
func (_e *StateRepo_Expecter) SetCopiedMessageID(chatID interface{}, messageID interface{}, toChatMessageID interface{}) *StateRepo_SetCopiedMessageID_Call {
	return &StateRepo_SetCopiedMessageID_Call{Call: _e.mock.On("SetCopiedMessageID", chatID, messageID, toChatMessageID)}
}

func (_c *StateRepo_SetCopiedMessageID_Call) Run(run func(chatID int64, messageID int64, toChatMessageID string)) *StateRepo_SetCopiedMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StateRepo_SetCopiedMessageID_Call) Return(err error) *StateRepo_SetCopiedMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateRepo_SetCopiedMessageID_Call) RunAndReturn(run func(chatID int64, messageID int64, toChatMessageID string) error) *StateRepo_SetCopiedMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// SetNewMessageID provides a mock function for the type StateRepo
func (_mock *StateRepo) SetNewMessageID(chatID int64, tmpMessageID int64, newMessageID int64) error {
	ret := _mock.Called(chatID, tmpMessageID, newMessageID)

	if len(ret) == 0 {
		panic("no return value specified for SetNewMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64, int64) error); ok {
		r0 = returnFunc(chatID, tmpMessageID, newMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateRepo_SetNewMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNewMessageID'
type StateRepo_SetNewMessageID_Call struct {
	*mock.Call
}

// SetNewMessageID is a helper method to define mock.On call
//   - chatID int64
//   - tmpMessageID int64
//   - newMessageID int64
func (_e *StateRepo_Expecter) SetNewMessageID(chatID interface{}, tmpMessageID interface{}, newMessageID interface{}) *StateRepo_SetNewMessageID_Call {
	return &StateRepo_SetNewMessageID_Call{Call: _e.mock.On("SetNewMessageID", chatID, tmpMessageID, newMessageID)}
}

func (_c *StateRepo_SetNewMessageID_Call) Run(run func(chatID int64, tmpMessageID int64, newMessageID int64)) *StateRepo_SetNewMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StateRepo_SetNewMessageID_Call) Return(err error) *StateRepo_SetNewMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateRepo_SetNewMessageID_Call) RunAndReturn(run func(chatID int64, tmpMessageID int64, newMessageID int64) error) *StateRepo_SetNewMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// SetTmpMessageID provides a mock function for the type StateRepo
func (_mock *StateRepo) SetTmpMessageID(chatID int64, newMessageID int64, tmpMessageID int64) error {
	ret := _mock.Called(chatID, newMessageID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for SetTmpMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64, int64) error); ok {
		r0 = returnFunc(chatID, newMessageID, tmpMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateRepo_SetTmpMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTmpMessageID'
type StateRepo_SetTmpMessageID_Call struct {
	*mock.Call
}

// SetTmpMessageID is a helper method to define mock.On call
//   - chatID int64
//   - newMessageID int64
//   - tmpMessageID int64
func (_e *StateRepo_Expecter) SetTmpMessageID(chatID interface{}, newMessageID interface{}, tmpMessageID interface{}) *StateRepo_SetTmpMessageID_Call {
	return &StateRepo_SetTmpMessageID_Call{Call: _e.mock.On("SetTmpMessageID", chatID, newMessageID, tmpMessageID)}
}

func (_c *StateRepo_SetTmpMessageID_Call) Run(run func(chatID int64, newMessageID int64, tmpMessageID int64)) *StateRepo_SetTmpMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StateRepo_SetTmpMessageID_Call) Return(err error) *StateRepo_SetTmpMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateRepo_SetTmpMessageID_Call) RunAndReturn(run func(chatID int64, newMessageID int64, tmpMessageID int64) error) *StateRepo_SetTmpMessageID_Call {
	_c.Call.Return(run)
	return _c
}
