// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/pure-golang/budva-claude/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewStateStore creates a new instance of StateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateStore {
	mock := &StateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StateStore is an autogenerated mock type for the stateStore type
type StateStore struct {
	mock.Mock
}

type StateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *StateStore) EXPECT() *StateStore_Expecter {
	return &StateStore_Expecter{mock: &_m.Mock}
}

// DeleteAnswerMessageID provides a mock function for the type StateStore
func (_mock *StateStore) DeleteAnswerMessageID(dstChatID domain.ChatID, tmpMessageID domain.MessageID) error {
	ret := _mock.Called(dstChatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAnswerMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, domain.MessageID) error); ok {
		r0 = returnFunc(dstChatID, tmpMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateStore_DeleteAnswerMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAnswerMessageID'
type StateStore_DeleteAnswerMessageID_Call struct {
	*mock.Call
}

// DeleteAnswerMessageID is a helper method to define mock.On call
//   - dstChatID domain.ChatID
//   - tmpMessageID domain.MessageID
func (_e *StateStore_Expecter) DeleteAnswerMessageID(dstChatID interface{}, tmpMessageID interface{}) *StateStore_DeleteAnswerMessageID_Call {
	return &StateStore_DeleteAnswerMessageID_Call{Call: _e.mock.On("DeleteAnswerMessageID", dstChatID, tmpMessageID)}
}

func (_c *StateStore_DeleteAnswerMessageID_Call) Run(run func(dstChatID domain.ChatID, tmpMessageID domain.MessageID)) *StateStore_DeleteAnswerMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 domain.MessageID
		if args[1] != nil {
			arg1 = args[1].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateStore_DeleteAnswerMessageID_Call) Return(err error) *StateStore_DeleteAnswerMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateStore_DeleteAnswerMessageID_Call) RunAndReturn(run func(dstChatID domain.ChatID, tmpMessageID domain.MessageID) error) *StateStore_DeleteAnswerMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCopiedMessageIDs provides a mock function for the type StateStore
func (_mock *StateStore) DeleteCopiedMessageIDs(chatID domain.ChatID, messageID domain.MessageID) error {
	ret := _mock.Called(chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCopiedMessageIDs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, domain.MessageID) error); ok {
		r0 = returnFunc(chatID, messageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateStore_DeleteCopiedMessageIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCopiedMessageIDs'
type StateStore_DeleteCopiedMessageIDs_Call struct {
	*mock.Call
}

// DeleteCopiedMessageIDs is a helper method to define mock.On call
//   - chatID domain.ChatID
//   - messageID domain.MessageID
func (_e *StateStore_Expecter) DeleteCopiedMessageIDs(chatID interface{}, messageID interface{}) *StateStore_DeleteCopiedMessageIDs_Call {
	return &StateStore_DeleteCopiedMessageIDs_Call{Call: _e.mock.On("DeleteCopiedMessageIDs", chatID, messageID)}
}

func (_c *StateStore_DeleteCopiedMessageIDs_Call) Run(run func(chatID domain.ChatID, messageID domain.MessageID)) *StateStore_DeleteCopiedMessageIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 domain.MessageID
		if args[1] != nil {
			arg1 = args[1].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateStore_DeleteCopiedMessageIDs_Call) Return(err error) *StateStore_DeleteCopiedMessageIDs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateStore_DeleteCopiedMessageIDs_Call) RunAndReturn(run func(chatID domain.ChatID, messageID domain.MessageID) error) *StateStore_DeleteCopiedMessageIDs_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNewMessageID provides a mock function for the type StateStore
func (_mock *StateStore) DeleteNewMessageID(chatID domain.ChatID, tmpMessageID domain.MessageID) error {
	ret := _mock.Called(chatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNewMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, domain.MessageID) error); ok {
		r0 = returnFunc(chatID, tmpMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateStore_DeleteNewMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNewMessageID'
type StateStore_DeleteNewMessageID_Call struct {
	*mock.Call
}

// DeleteNewMessageID is a helper method to define mock.On call
//   - chatID domain.ChatID
//   - tmpMessageID domain.MessageID
func (_e *StateStore_Expecter) DeleteNewMessageID(chatID interface{}, tmpMessageID interface{}) *StateStore_DeleteNewMessageID_Call {
	return &StateStore_DeleteNewMessageID_Call{Call: _e.mock.On("DeleteNewMessageID", chatID, tmpMessageID)}
}

func (_c *StateStore_DeleteNewMessageID_Call) Run(run func(chatID domain.ChatID, tmpMessageID domain.MessageID)) *StateStore_DeleteNewMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 domain.MessageID
		if args[1] != nil {
			arg1 = args[1].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateStore_DeleteNewMessageID_Call) Return(err error) *StateStore_DeleteNewMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateStore_DeleteNewMessageID_Call) RunAndReturn(run func(chatID domain.ChatID, tmpMessageID domain.MessageID) error) *StateStore_DeleteNewMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTmpMessageID provides a mock function for the type StateStore
func (_mock *StateStore) DeleteTmpMessageID(chatID domain.ChatID, newMessageID domain.MessageID) error {
	ret := _mock.Called(chatID, newMessageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTmpMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, domain.MessageID) error); ok {
		r0 = returnFunc(chatID, newMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateStore_DeleteTmpMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTmpMessageID'
type StateStore_DeleteTmpMessageID_Call struct {
	*mock.Call
}

// DeleteTmpMessageID is a helper method to define mock.On call
//   - chatID domain.ChatID
//   - newMessageID domain.MessageID
func (_e *StateStore_Expecter) DeleteTmpMessageID(chatID interface{}, newMessageID interface{}) *StateStore_DeleteTmpMessageID_Call {
	return &StateStore_DeleteTmpMessageID_Call{Call: _e.mock.On("DeleteTmpMessageID", chatID, newMessageID)}
}

func (_c *StateStore_DeleteTmpMessageID_Call) Run(run func(chatID domain.ChatID, newMessageID domain.MessageID)) *StateStore_DeleteTmpMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 domain.MessageID
		if args[1] != nil {
			arg1 = args[1].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateStore_DeleteTmpMessageID_Call) Return(err error) *StateStore_DeleteTmpMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateStore_DeleteTmpMessageID_Call) RunAndReturn(run func(chatID domain.ChatID, newMessageID domain.MessageID) error) *StateStore_DeleteTmpMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnswerMessageID provides a mock function for the type StateStore
func (_mock *StateStore) GetAnswerMessageID(dstChatID domain.ChatID, tmpMessageID domain.MessageID) string {
	ret := _mock.Called(dstChatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for GetAnswerMessageID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, domain.MessageID) string); ok {
		r0 = returnFunc(dstChatID, tmpMessageID)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// StateStore_GetAnswerMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnswerMessageID'
type StateStore_GetAnswerMessageID_Call struct {
	*mock.Call
}

// GetAnswerMessageID is a helper method to define mock.On call
//   - dstChatID domain.ChatID
//   - tmpMessageID domain.MessageID
func (_e *StateStore_Expecter) GetAnswerMessageID(dstChatID interface{}, tmpMessageID interface{}) *StateStore_GetAnswerMessageID_Call {
	return &StateStore_GetAnswerMessageID_Call{Call: _e.mock.On("GetAnswerMessageID", dstChatID, tmpMessageID)}
}

func (_c *StateStore_GetAnswerMessageID_Call) Run(run func(dstChatID domain.ChatID, tmpMessageID domain.MessageID)) *StateStore_GetAnswerMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 domain.MessageID
		if args[1] != nil {
			arg1 = args[1].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateStore_GetAnswerMessageID_Call) Return(s string) *StateStore_GetAnswerMessageID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *StateStore_GetAnswerMessageID_Call) RunAndReturn(run func(dstChatID domain.ChatID, tmpMessageID domain.MessageID) string) *StateStore_GetAnswerMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCopiedMessageIDs provides a mock function for the type StateStore
func (_mock *StateStore) GetCopiedMessageIDs(chatID domain.ChatID, messageID domain.MessageID) []string {
	ret := _mock.Called(chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetCopiedMessageIDs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, domain.MessageID) []string); ok {
		r0 = returnFunc(chatID, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// StateStore_GetCopiedMessageIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCopiedMessageIDs'
type StateStore_GetCopiedMessageIDs_Call struct {
	*mock.Call
}

// GetCopiedMessageIDs is a helper method to define mock.On call
//   - chatID domain.ChatID
//   - messageID domain.MessageID
func (_e *StateStore_Expecter) GetCopiedMessageIDs(chatID interface{}, messageID interface{}) *StateStore_GetCopiedMessageIDs_Call {
	return &StateStore_GetCopiedMessageIDs_Call{Call: _e.mock.On("GetCopiedMessageIDs", chatID, messageID)}
}

func (_c *StateStore_GetCopiedMessageIDs_Call) Run(run func(chatID domain.ChatID, messageID domain.MessageID)) *StateStore_GetCopiedMessageIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 domain.MessageID
		if args[1] != nil {
			arg1 = args[1].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateStore_GetCopiedMessageIDs_Call) Return(strings []string) *StateStore_GetCopiedMessageIDs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *StateStore_GetCopiedMessageIDs_Call) RunAndReturn(run func(chatID domain.ChatID, messageID domain.MessageID) []string) *StateStore_GetCopiedMessageIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewMessageID provides a mock function for the type StateStore
func (_mock *StateStore) GetNewMessageID(chatID domain.ChatID, tmpMessageID domain.MessageID) domain.MessageID {
	ret := _mock.Called(chatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for GetNewMessageID")
	}

	var r0 domain.MessageID
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, domain.MessageID) domain.MessageID); ok {
		r0 = returnFunc(chatID, tmpMessageID)
	} else {
		r0 = ret.Get(0).(domain.MessageID)
	}
	return r0
}

// StateStore_GetNewMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewMessageID'
type StateStore_GetNewMessageID_Call struct {
	*mock.Call
}

// GetNewMessageID is a helper method to define mock.On call
//   - chatID domain.ChatID
//   - tmpMessageID domain.MessageID
func (_e *StateStore_Expecter) GetNewMessageID(chatID interface{}, tmpMessageID interface{}) *StateStore_GetNewMessageID_Call {
	return &StateStore_GetNewMessageID_Call{Call: _e.mock.On("GetNewMessageID", chatID, tmpMessageID)}
}

func (_c *StateStore_GetNewMessageID_Call) Run(run func(chatID domain.ChatID, tmpMessageID domain.MessageID)) *StateStore_GetNewMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 domain.MessageID
		if args[1] != nil {
			arg1 = args[1].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateStore_GetNewMessageID_Call) Return(v domain.MessageID) *StateStore_GetNewMessageID_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *StateStore_GetNewMessageID_Call) RunAndReturn(run func(chatID domain.ChatID, tmpMessageID domain.MessageID) domain.MessageID) *StateStore_GetNewMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementForwardedMessages provides a mock function for the type StateStore
func (_mock *StateStore) IncrementForwardedMessages(toChatID domain.ChatID, date string) (uint64, error) {
	ret := _mock.Called(toChatID, date)

	if len(ret) == 0 {
		panic("no return value specified for IncrementForwardedMessages")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, string) (uint64, error)); ok {
		return returnFunc(toChatID, date)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, string) uint64); ok {
		r0 = returnFunc(toChatID, date)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.ChatID, string) error); ok {
		r1 = returnFunc(toChatID, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StateStore_IncrementForwardedMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementForwardedMessages'
type StateStore_IncrementForwardedMessages_Call struct {
	*mock.Call
}

// IncrementForwardedMessages is a helper method to define mock.On call
//   - toChatID domain.ChatID
//   - date string
func (_e *StateStore_Expecter) IncrementForwardedMessages(toChatID interface{}, date interface{}) *StateStore_IncrementForwardedMessages_Call {
	return &StateStore_IncrementForwardedMessages_Call{Call: _e.mock.On("IncrementForwardedMessages", toChatID, date)}
}

func (_c *StateStore_IncrementForwardedMessages_Call) Run(run func(toChatID domain.ChatID, date string)) *StateStore_IncrementForwardedMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateStore_IncrementForwardedMessages_Call) Return(v uint64, err error) *StateStore_IncrementForwardedMessages_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *StateStore_IncrementForwardedMessages_Call) RunAndReturn(run func(toChatID domain.ChatID, date string) (uint64, error)) *StateStore_IncrementForwardedMessages_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementViewedMessages provides a mock function for the type StateStore
func (_mock *StateStore) IncrementViewedMessages(toChatID domain.ChatID, date string) (uint64, error) {
	ret := _mock.Called(toChatID, date)

	if len(ret) == 0 {
		panic("no return value specified for IncrementViewedMessages")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, string) (uint64, error)); ok {
		return returnFunc(toChatID, date)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, string) uint64); ok {
		r0 = returnFunc(toChatID, date)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.ChatID, string) error); ok {
		r1 = returnFunc(toChatID, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StateStore_IncrementViewedMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementViewedMessages'
type StateStore_IncrementViewedMessages_Call struct {
	*mock.Call
}

// IncrementViewedMessages is a helper method to define mock.On call
//   - toChatID domain.ChatID
//   - date string
func (_e *StateStore_Expecter) IncrementViewedMessages(toChatID interface{}, date interface{}) *StateStore_IncrementViewedMessages_Call {
	return &StateStore_IncrementViewedMessages_Call{Call: _e.mock.On("IncrementViewedMessages", toChatID, date)}
}

func (_c *StateStore_IncrementViewedMessages_Call) Run(run func(toChatID domain.ChatID, date string)) *StateStore_IncrementViewedMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateStore_IncrementViewedMessages_Call) Return(v uint64, err error) *StateStore_IncrementViewedMessages_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *StateStore_IncrementViewedMessages_Call) RunAndReturn(run func(toChatID domain.ChatID, date string) (uint64, error)) *StateStore_IncrementViewedMessages_Call {
	_c.Call.Return(run)
	return _c
}

// SetAnswerMessageID provides a mock function for the type StateStore
func (_mock *StateStore) SetAnswerMessageID(dstChatID domain.ChatID, tmpMessageID domain.MessageID, srcChatID domain.ChatID, srcMessageID domain.MessageID) error {
	ret := _mock.Called(dstChatID, tmpMessageID, srcChatID, srcMessageID)

	if len(ret) == 0 {
		panic("no return value specified for SetAnswerMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, domain.MessageID, domain.ChatID, domain.MessageID) error); ok {
		r0 = returnFunc(dstChatID, tmpMessageID, srcChatID, srcMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateStore_SetAnswerMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAnswerMessageID'
type StateStore_SetAnswerMessageID_Call struct {
	*mock.Call
}

// SetAnswerMessageID is a helper method to define mock.On call
//   - dstChatID domain.ChatID
//   - tmpMessageID domain.MessageID
//   - srcChatID domain.ChatID
//   - srcMessageID domain.MessageID
func (_e *StateStore_Expecter) SetAnswerMessageID(dstChatID interface{}, tmpMessageID interface{}, srcChatID interface{}, srcMessageID interface{}) *StateStore_SetAnswerMessageID_Call {
	return &StateStore_SetAnswerMessageID_Call{Call: _e.mock.On("SetAnswerMessageID", dstChatID, tmpMessageID, srcChatID, srcMessageID)}
}

func (_c *StateStore_SetAnswerMessageID_Call) Run(run func(dstChatID domain.ChatID, tmpMessageID domain.MessageID, srcChatID domain.ChatID, srcMessageID domain.MessageID)) *StateStore_SetAnswerMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 domain.MessageID
		if args[1] != nil {
			arg1 = args[1].(domain.MessageID)
		}
		var arg2 domain.ChatID
		if args[2] != nil {
			arg2 = args[2].(domain.ChatID)
		}
		var arg3 domain.MessageID
		if args[3] != nil {
			arg3 = args[3].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *StateStore_SetAnswerMessageID_Call) Return(err error) *StateStore_SetAnswerMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateStore_SetAnswerMessageID_Call) RunAndReturn(run func(dstChatID domain.ChatID, tmpMessageID domain.MessageID, srcChatID domain.ChatID, srcMessageID domain.MessageID) error) *StateStore_SetAnswerMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// SetCopiedMessageID provides a mock function for the type StateStore
func (_mock *StateStore) SetCopiedMessageID(chatID domain.ChatID, messageID domain.MessageID, toChatMessageID string) error {
	ret := _mock.Called(chatID, messageID, toChatMessageID)

	if len(ret) == 0 {
		panic("no return value specified for SetCopiedMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, domain.MessageID, string) error); ok {
		r0 = returnFunc(chatID, messageID, toChatMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateStore_SetCopiedMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCopiedMessageID'
type StateStore_SetCopiedMessageID_Call struct {
	*mock.Call
}

// SetCopiedMessageID is a helper method to define mock.On call
//   - chatID domain.ChatID
//   - messageID domain.MessageID
//   - toChatMessageID string
func (_e *StateStore_Expecter) SetCopiedMessageID(chatID interface{}, messageID interface{}, toChatMessageID interface{}) *StateStore_SetCopiedMessageID_Call {
	return &StateStore_SetCopiedMessageID_Call{Call: _e.mock.On("SetCopiedMessageID", chatID, messageID, toChatMessageID)}
}

func (_c *StateStore_SetCopiedMessageID_Call) Run(run func(chatID domain.ChatID, messageID domain.MessageID, toChatMessageID string)) *StateStore_SetCopiedMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 domain.MessageID
		if args[1] != nil {
			arg1 = args[1].(domain.MessageID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StateStore_SetCopiedMessageID_Call) Return(err error) *StateStore_SetCopiedMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateStore_SetCopiedMessageID_Call) RunAndReturn(run func(chatID domain.ChatID, messageID domain.MessageID, toChatMessageID string) error) *StateStore_SetCopiedMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// SetNewMessageID provides a mock function for the type StateStore
func (_mock *StateStore) SetNewMessageID(chatID domain.ChatID, tmpMessageID domain.MessageID, newMessageID domain.MessageID) error {
	ret := _mock.Called(chatID, tmpMessageID, newMessageID)

	if len(ret) == 0 {
		panic("no return value specified for SetNewMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, domain.MessageID, domain.MessageID) error); ok {
		r0 = returnFunc(chatID, tmpMessageID, newMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateStore_SetNewMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNewMessageID'
type StateStore_SetNewMessageID_Call struct {
	*mock.Call
}

// SetNewMessageID is a helper method to define mock.On call
//   - chatID domain.ChatID
//   - tmpMessageID domain.MessageID
//   - newMessageID domain.MessageID
func (_e *StateStore_Expecter) SetNewMessageID(chatID interface{}, tmpMessageID interface{}, newMessageID interface{}) *StateStore_SetNewMessageID_Call {
	return &StateStore_SetNewMessageID_Call{Call: _e.mock.On("SetNewMessageID", chatID, tmpMessageID, newMessageID)}
}

func (_c *StateStore_SetNewMessageID_Call) Run(run func(chatID domain.ChatID, tmpMessageID domain.MessageID, newMessageID domain.MessageID)) *StateStore_SetNewMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 domain.MessageID
		if args[1] != nil {
			arg1 = args[1].(domain.MessageID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StateStore_SetNewMessageID_Call) Return(err error) *StateStore_SetNewMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateStore_SetNewMessageID_Call) RunAndReturn(run func(chatID domain.ChatID, tmpMessageID domain.MessageID, newMessageID domain.MessageID) error) *StateStore_SetNewMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// SetTmpMessageID provides a mock function for the type StateStore
func (_mock *StateStore) SetTmpMessageID(chatID domain.ChatID, newMessageID domain.MessageID, tmpMessageID domain.MessageID) error {
	ret := _mock.Called(chatID, newMessageID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for SetTmpMessageID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, domain.MessageID, domain.MessageID) error); ok {
		r0 = returnFunc(chatID, newMessageID, tmpMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateStore_SetTmpMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTmpMessageID'
type StateStore_SetTmpMessageID_Call struct {
	*mock.Call
}

// SetTmpMessageID is a helper method to define mock.On call
//   - chatID domain.ChatID
//   - newMessageID domain.MessageID
//   - tmpMessageID domain.MessageID
func (_e *StateStore_Expecter) SetTmpMessageID(chatID interface{}, newMessageID interface{}, tmpMessageID interface{}) *StateStore_SetTmpMessageID_Call {
	return &StateStore_SetTmpMessageID_Call{Call: _e.mock.On("SetTmpMessageID", chatID, newMessageID, tmpMessageID)}
}

func (_c *StateStore_SetTmpMessageID_Call) Run(run func(chatID domain.ChatID, newMessageID domain.MessageID, tmpMessageID domain.MessageID)) *StateStore_SetTmpMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 domain.MessageID
		if args[1] != nil {
			arg1 = args[1].(domain.MessageID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StateStore_SetTmpMessageID_Call) Return(err error) *StateStore_SetTmpMessageID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateStore_SetTmpMessageID_Call) RunAndReturn(run func(chatID domain.ChatID, newMessageID domain.MessageID, tmpMessageID domain.MessageID) error) *StateStore_SetTmpMessageID_Call {
	_c.Call.Return(run)
	return _c
}
