// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/pure-golang/budva-claude/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTransformService creates a new instance of TransformService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransformService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransformService {
	mock := &TransformService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TransformService is an autogenerated mock type for the transformService type
type TransformService struct {
	mock.Mock
}

type TransformService_Expecter struct {
	mock *mock.Mock
}

func (_m *TransformService) EXPECT() *TransformService_Expecter {
	return &TransformService_Expecter{mock: &_m.Mock}
}

// AddNextLink provides a mock function for the type TransformService
func (_mock *TransformService) AddNextLink(ctx context.Context, text *domain.FormattedText, src *domain.Source, dstChatID domain.ChatID, nextMessageID domain.MessageID) *domain.FormattedText {
	ret := _mock.Called(ctx, text, src, dstChatID, nextMessageID)

	if len(ret) == 0 {
		panic("no return value specified for AddNextLink")
	}

	var r0 *domain.FormattedText
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.FormattedText, *domain.Source, domain.ChatID, domain.MessageID) *domain.FormattedText); ok {
		r0 = returnFunc(ctx, text, src, dstChatID, nextMessageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FormattedText)
		}
	}
	return r0
}

// TransformService_AddNextLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNextLink'
type TransformService_AddNextLink_Call struct {
	*mock.Call
}

// AddNextLink is a helper method to define mock.On call
//   - ctx context.Context
//   - text *domain.FormattedText
//   - src *domain.Source
//   - dstChatID domain.ChatID
//   - nextMessageID domain.MessageID
func (_e *TransformService_Expecter) AddNextLink(ctx interface{}, text interface{}, src interface{}, dstChatID interface{}, nextMessageID interface{}) *TransformService_AddNextLink_Call {
	return &TransformService_AddNextLink_Call{Call: _e.mock.On("AddNextLink", ctx, text, src, dstChatID, nextMessageID)}
}

func (_c *TransformService_AddNextLink_Call) Run(run func(ctx context.Context, text *domain.FormattedText, src *domain.Source, dstChatID domain.ChatID, nextMessageID domain.MessageID)) *TransformService_AddNextLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.FormattedText
		if args[1] != nil {
			arg1 = args[1].(*domain.FormattedText)
		}
		var arg2 *domain.Source
		if args[2] != nil {
			arg2 = args[2].(*domain.Source)
		}
		var arg3 domain.ChatID
		if args[3] != nil {
			arg3 = args[3].(domain.ChatID)
		}
		var arg4 domain.MessageID
		if args[4] != nil {
			arg4 = args[4].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TransformService_AddNextLink_Call) Return(formattedText *domain.FormattedText) *TransformService_AddNextLink_Call {
	_c.Call.Return(formattedText)
	return _c
}

func (_c *TransformService_AddNextLink_Call) RunAndReturn(run func(ctx context.Context, text *domain.FormattedText, src *domain.Source, dstChatID domain.ChatID, nextMessageID domain.MessageID) *domain.FormattedText) *TransformService_AddNextLink_Call {
	_c.Call.Return(run)
	return _c
}

// Transform provides a mock function for the type TransformService
func (_mock *TransformService) Transform(ctx context.Context, params domain.TransformParams) (*domain.FormattedText, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Transform")
	}

	var r0 *domain.FormattedText
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TransformParams) (*domain.FormattedText, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TransformParams) *domain.FormattedText); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FormattedText)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.TransformParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransformService_Transform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transform'
type TransformService_Transform_Call struct {
	*mock.Call
}

// Transform is a helper method to define mock.On call
//   - ctx context.Context
//   - params domain.TransformParams
func (_e *TransformService_Expecter) Transform(ctx interface{}, params interface{}) *TransformService_Transform_Call {
	return &TransformService_Transform_Call{Call: _e.mock.On("Transform", ctx, params)}
}

func (_c *TransformService_Transform_Call) Run(run func(ctx context.Context, params domain.TransformParams)) *TransformService_Transform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TransformParams
		if args[1] != nil {
			arg1 = args[1].(domain.TransformParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransformService_Transform_Call) Return(formattedText *domain.FormattedText, err error) *TransformService_Transform_Call {
	_c.Call.Return(formattedText, err)
	return _c
}

func (_c *TransformService_Transform_Call) RunAndReturn(run func(ctx context.Context, params domain.TransformParams) (*domain.FormattedText, error)) *TransformService_Transform_Call {
	_c.Call.Return(run)
	return _c
}
