filename: "{{.InterfaceName | snakecase}}.go"
dir: "{{.InterfaceDir}}/mocks"
structname: "{{.InterfaceName | firstUpper}}"
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/pure-golang/budva-claude/internal/app/handler:
    config:
      all: true
  github.com/pure-golang/budva-claude/internal/infra/telegram:
    config:
      all: true
  github.com/pure-golang/budva-claude/internal/service/transform:
    config:
      all: true
  github.com/pure-golang/budva-claude/internal/transport/http/health:
    config:
      all: true
  github.com/pure-golang/budva-claude/internal/app/facade:
    config:
      all: true
  github.com/pure-golang/budva-claude/internal/app/auth:
    config:
      all: true
  github.com/pure-golang/budva-claude/internal/transport/http:
    config:
      all: true
  github.com/pure-golang/budva-claude/internal/transport/grpc:
    config:
      all: true
  github.com/pure-golang/budva-claude/internal/transport/http/resolvers:
    config:
      all: true
