filename: "{{.InterfaceName | snakecase}}.go"
dir: "{{.InterfaceDir}}/mocks"
structname: "{{.InterfaceName | firstUpper}}"
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/pure-golang/budva-claude/internal/handler:
    config:
      all: true
  github.com/pure-golang/budva-claude/internal/service/transform:
    config:
      all: true
  github.com/pure-golang/budva-claude/internal/controller:
    config:
      all: true
