// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTaskQueue creates a new instance of TaskQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskQueue {
	mock := &TaskQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TaskQueue is an autogenerated mock type for the taskQueue type
type TaskQueue struct {
	mock.Mock
}

type TaskQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskQueue) EXPECT() *TaskQueue_Expecter {
	return &TaskQueue_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type TaskQueue
func (_mock *TaskQueue) Add(fn func()) {
	_mock.Called(fn)
	return
}

// TaskQueue_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type TaskQueue_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - fn func()
func (_e *TaskQueue_Expecter) Add(fn interface{}) *TaskQueue_Add_Call {
	return &TaskQueue_Add_Call{Call: _e.mock.On("Add", fn)}
}

func (_c *TaskQueue_Add_Call) Run(run func(fn func())) *TaskQueue_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func()
		if args[0] != nil {
			arg0 = args[0].(func())
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskQueue_Add_Call) Return() *TaskQueue_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *TaskQueue_Add_Call) RunAndReturn(run func(fn func())) *TaskQueue_Add_Call {
	_c.Run(run)
	return _c
}
