// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/zelenin/go-tdlib/client"
)

// NewTelegramRepo creates a new instance of TelegramRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramRepo {
	mock := &TelegramRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TelegramRepo is an autogenerated mock type for the telegramRepo type
type TelegramRepo struct {
	mock.Mock
}

type TelegramRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramRepo) EXPECT() *TelegramRepo_Expecter {
	return &TelegramRepo_Expecter{mock: &_m.Mock}
}

// ClientDone provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) ClientDone() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClientDone")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// TelegramRepo_ClientDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientDone'
type TelegramRepo_ClientDone_Call struct {
	*mock.Call
}

// ClientDone is a helper method to define mock.On call
func (_e *TelegramRepo_Expecter) ClientDone() *TelegramRepo_ClientDone_Call {
	return &TelegramRepo_ClientDone_Call{Call: _e.mock.On("ClientDone")}
}

func (_c *TelegramRepo_ClientDone_Call) Run(run func()) *TelegramRepo_ClientDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TelegramRepo_ClientDone_Call) Return(valCh <-chan struct{}) *TelegramRepo_ClientDone_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *TelegramRepo_ClientDone_Call) RunAndReturn(run func() <-chan struct{}) *TelegramRepo_ClientDone_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessages provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) DeleteMessages(deleteMessagesRequest *client.DeleteMessagesRequest) (*client.Ok, error) {
	ret := _mock.Called(deleteMessagesRequest)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessages")
	}

	var r0 *client.Ok
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*client.DeleteMessagesRequest) (*client.Ok, error)); ok {
		return returnFunc(deleteMessagesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*client.DeleteMessagesRequest) *client.Ok); ok {
		r0 = returnFunc(deleteMessagesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Ok)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*client.DeleteMessagesRequest) error); ok {
		r1 = returnFunc(deleteMessagesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_DeleteMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessages'
type TelegramRepo_DeleteMessages_Call struct {
	*mock.Call
}

// DeleteMessages is a helper method to define mock.On call
//   - deleteMessagesRequest *client.DeleteMessagesRequest
func (_e *TelegramRepo_Expecter) DeleteMessages(deleteMessagesRequest interface{}) *TelegramRepo_DeleteMessages_Call {
	return &TelegramRepo_DeleteMessages_Call{Call: _e.mock.On("DeleteMessages", deleteMessagesRequest)}
}

func (_c *TelegramRepo_DeleteMessages_Call) Run(run func(deleteMessagesRequest *client.DeleteMessagesRequest)) *TelegramRepo_DeleteMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *client.DeleteMessagesRequest
		if args[0] != nil {
			arg0 = args[0].(*client.DeleteMessagesRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_DeleteMessages_Call) Return(ok *client.Ok, err error) *TelegramRepo_DeleteMessages_Call {
	_c.Call.Return(ok, err)
	return _c
}

func (_c *TelegramRepo_DeleteMessages_Call) RunAndReturn(run func(deleteMessagesRequest *client.DeleteMessagesRequest) (*client.Ok, error)) *TelegramRepo_DeleteMessages_Call {
	_c.Call.Return(run)
	return _c
}

// EditMessageCaption provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) EditMessageCaption(editMessageCaptionRequest *client.EditMessageCaptionRequest) (*client.Message, error) {
	ret := _mock.Called(editMessageCaptionRequest)

	if len(ret) == 0 {
		panic("no return value specified for EditMessageCaption")
	}

	var r0 *client.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*client.EditMessageCaptionRequest) (*client.Message, error)); ok {
		return returnFunc(editMessageCaptionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*client.EditMessageCaptionRequest) *client.Message); ok {
		r0 = returnFunc(editMessageCaptionRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*client.EditMessageCaptionRequest) error); ok {
		r1 = returnFunc(editMessageCaptionRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_EditMessageCaption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditMessageCaption'
type TelegramRepo_EditMessageCaption_Call struct {
	*mock.Call
}

// EditMessageCaption is a helper method to define mock.On call
//   - editMessageCaptionRequest *client.EditMessageCaptionRequest
func (_e *TelegramRepo_Expecter) EditMessageCaption(editMessageCaptionRequest interface{}) *TelegramRepo_EditMessageCaption_Call {
	return &TelegramRepo_EditMessageCaption_Call{Call: _e.mock.On("EditMessageCaption", editMessageCaptionRequest)}
}

func (_c *TelegramRepo_EditMessageCaption_Call) Run(run func(editMessageCaptionRequest *client.EditMessageCaptionRequest)) *TelegramRepo_EditMessageCaption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *client.EditMessageCaptionRequest
		if args[0] != nil {
			arg0 = args[0].(*client.EditMessageCaptionRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_EditMessageCaption_Call) Return(message *client.Message, err error) *TelegramRepo_EditMessageCaption_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *TelegramRepo_EditMessageCaption_Call) RunAndReturn(run func(editMessageCaptionRequest *client.EditMessageCaptionRequest) (*client.Message, error)) *TelegramRepo_EditMessageCaption_Call {
	_c.Call.Return(run)
	return _c
}

// EditMessageText provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) EditMessageText(editMessageTextRequest *client.EditMessageTextRequest) (*client.Message, error) {
	ret := _mock.Called(editMessageTextRequest)

	if len(ret) == 0 {
		panic("no return value specified for EditMessageText")
	}

	var r0 *client.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*client.EditMessageTextRequest) (*client.Message, error)); ok {
		return returnFunc(editMessageTextRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*client.EditMessageTextRequest) *client.Message); ok {
		r0 = returnFunc(editMessageTextRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*client.EditMessageTextRequest) error); ok {
		r1 = returnFunc(editMessageTextRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_EditMessageText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditMessageText'
type TelegramRepo_EditMessageText_Call struct {
	*mock.Call
}

// EditMessageText is a helper method to define mock.On call
//   - editMessageTextRequest *client.EditMessageTextRequest
func (_e *TelegramRepo_Expecter) EditMessageText(editMessageTextRequest interface{}) *TelegramRepo_EditMessageText_Call {
	return &TelegramRepo_EditMessageText_Call{Call: _e.mock.On("EditMessageText", editMessageTextRequest)}
}

func (_c *TelegramRepo_EditMessageText_Call) Run(run func(editMessageTextRequest *client.EditMessageTextRequest)) *TelegramRepo_EditMessageText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *client.EditMessageTextRequest
		if args[0] != nil {
			arg0 = args[0].(*client.EditMessageTextRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_EditMessageText_Call) Return(message *client.Message, err error) *TelegramRepo_EditMessageText_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *TelegramRepo_EditMessageText_Call) RunAndReturn(run func(editMessageTextRequest *client.EditMessageTextRequest) (*client.Message, error)) *TelegramRepo_EditMessageText_Call {
	_c.Call.Return(run)
	return _c
}

// ForwardMessages provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) ForwardMessages(forwardMessagesRequest *client.ForwardMessagesRequest) (*client.Messages, error) {
	ret := _mock.Called(forwardMessagesRequest)

	if len(ret) == 0 {
		panic("no return value specified for ForwardMessages")
	}

	var r0 *client.Messages
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*client.ForwardMessagesRequest) (*client.Messages, error)); ok {
		return returnFunc(forwardMessagesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*client.ForwardMessagesRequest) *client.Messages); ok {
		r0 = returnFunc(forwardMessagesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Messages)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*client.ForwardMessagesRequest) error); ok {
		r1 = returnFunc(forwardMessagesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_ForwardMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForwardMessages'
type TelegramRepo_ForwardMessages_Call struct {
	*mock.Call
}

// ForwardMessages is a helper method to define mock.On call
//   - forwardMessagesRequest *client.ForwardMessagesRequest
func (_e *TelegramRepo_Expecter) ForwardMessages(forwardMessagesRequest interface{}) *TelegramRepo_ForwardMessages_Call {
	return &TelegramRepo_ForwardMessages_Call{Call: _e.mock.On("ForwardMessages", forwardMessagesRequest)}
}

func (_c *TelegramRepo_ForwardMessages_Call) Run(run func(forwardMessagesRequest *client.ForwardMessagesRequest)) *TelegramRepo_ForwardMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *client.ForwardMessagesRequest
		if args[0] != nil {
			arg0 = args[0].(*client.ForwardMessagesRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_ForwardMessages_Call) Return(messages *client.Messages, err error) *TelegramRepo_ForwardMessages_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *TelegramRepo_ForwardMessages_Call) RunAndReturn(run func(forwardMessagesRequest *client.ForwardMessagesRequest) (*client.Messages, error)) *TelegramRepo_ForwardMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessage provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetMessage(getMessageRequest *client.GetMessageRequest) (*client.Message, error) {
	ret := _mock.Called(getMessageRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 *client.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*client.GetMessageRequest) (*client.Message, error)); ok {
		return returnFunc(getMessageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*client.GetMessageRequest) *client.Message); ok {
		r0 = returnFunc(getMessageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*client.GetMessageRequest) error); ok {
		r1 = returnFunc(getMessageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessage'
type TelegramRepo_GetMessage_Call struct {
	*mock.Call
}

// GetMessage is a helper method to define mock.On call
//   - getMessageRequest *client.GetMessageRequest
func (_e *TelegramRepo_Expecter) GetMessage(getMessageRequest interface{}) *TelegramRepo_GetMessage_Call {
	return &TelegramRepo_GetMessage_Call{Call: _e.mock.On("GetMessage", getMessageRequest)}
}

func (_c *TelegramRepo_GetMessage_Call) Run(run func(getMessageRequest *client.GetMessageRequest)) *TelegramRepo_GetMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *client.GetMessageRequest
		if args[0] != nil {
			arg0 = args[0].(*client.GetMessageRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetMessage_Call) Return(message *client.Message, err error) *TelegramRepo_GetMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *TelegramRepo_GetMessage_Call) RunAndReturn(run func(getMessageRequest *client.GetMessageRequest) (*client.Message, error)) *TelegramRepo_GetMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageLink provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetMessageLink(getMessageLinkRequest *client.GetMessageLinkRequest) (*client.MessageLink, error) {
	ret := _mock.Called(getMessageLinkRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageLink")
	}

	var r0 *client.MessageLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*client.GetMessageLinkRequest) (*client.MessageLink, error)); ok {
		return returnFunc(getMessageLinkRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*client.GetMessageLinkRequest) *client.MessageLink); ok {
		r0 = returnFunc(getMessageLinkRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.MessageLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*client.GetMessageLinkRequest) error); ok {
		r1 = returnFunc(getMessageLinkRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetMessageLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageLink'
type TelegramRepo_GetMessageLink_Call struct {
	*mock.Call
}

// GetMessageLink is a helper method to define mock.On call
//   - getMessageLinkRequest *client.GetMessageLinkRequest
func (_e *TelegramRepo_Expecter) GetMessageLink(getMessageLinkRequest interface{}) *TelegramRepo_GetMessageLink_Call {
	return &TelegramRepo_GetMessageLink_Call{Call: _e.mock.On("GetMessageLink", getMessageLinkRequest)}
}

func (_c *TelegramRepo_GetMessageLink_Call) Run(run func(getMessageLinkRequest *client.GetMessageLinkRequest)) *TelegramRepo_GetMessageLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *client.GetMessageLinkRequest
		if args[0] != nil {
			arg0 = args[0].(*client.GetMessageLinkRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetMessageLink_Call) Return(messageLink *client.MessageLink, err error) *TelegramRepo_GetMessageLink_Call {
	_c.Call.Return(messageLink, err)
	return _c
}

func (_c *TelegramRepo_GetMessageLink_Call) RunAndReturn(run func(getMessageLinkRequest *client.GetMessageLinkRequest) (*client.MessageLink, error)) *TelegramRepo_GetMessageLink_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) SendMessage(sendMessageRequest *client.SendMessageRequest) (*client.Message, error) {
	ret := _mock.Called(sendMessageRequest)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *client.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*client.SendMessageRequest) (*client.Message, error)); ok {
		return returnFunc(sendMessageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*client.SendMessageRequest) *client.Message); ok {
		r0 = returnFunc(sendMessageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*client.SendMessageRequest) error); ok {
		r1 = returnFunc(sendMessageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type TelegramRepo_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - sendMessageRequest *client.SendMessageRequest
func (_e *TelegramRepo_Expecter) SendMessage(sendMessageRequest interface{}) *TelegramRepo_SendMessage_Call {
	return &TelegramRepo_SendMessage_Call{Call: _e.mock.On("SendMessage", sendMessageRequest)}
}

func (_c *TelegramRepo_SendMessage_Call) Run(run func(sendMessageRequest *client.SendMessageRequest)) *TelegramRepo_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *client.SendMessageRequest
		if args[0] != nil {
			arg0 = args[0].(*client.SendMessageRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_SendMessage_Call) Return(message *client.Message, err error) *TelegramRepo_SendMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *TelegramRepo_SendMessage_Call) RunAndReturn(run func(sendMessageRequest *client.SendMessageRequest) (*client.Message, error)) *TelegramRepo_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessageAlbum provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) SendMessageAlbum(sendMessageAlbumRequest *client.SendMessageAlbumRequest) (*client.Messages, error) {
	ret := _mock.Called(sendMessageAlbumRequest)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageAlbum")
	}

	var r0 *client.Messages
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*client.SendMessageAlbumRequest) (*client.Messages, error)); ok {
		return returnFunc(sendMessageAlbumRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*client.SendMessageAlbumRequest) *client.Messages); ok {
		r0 = returnFunc(sendMessageAlbumRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Messages)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*client.SendMessageAlbumRequest) error); ok {
		r1 = returnFunc(sendMessageAlbumRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_SendMessageAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageAlbum'
type TelegramRepo_SendMessageAlbum_Call struct {
	*mock.Call
}

// SendMessageAlbum is a helper method to define mock.On call
//   - sendMessageAlbumRequest *client.SendMessageAlbumRequest
func (_e *TelegramRepo_Expecter) SendMessageAlbum(sendMessageAlbumRequest interface{}) *TelegramRepo_SendMessageAlbum_Call {
	return &TelegramRepo_SendMessageAlbum_Call{Call: _e.mock.On("SendMessageAlbum", sendMessageAlbumRequest)}
}

func (_c *TelegramRepo_SendMessageAlbum_Call) Run(run func(sendMessageAlbumRequest *client.SendMessageAlbumRequest)) *TelegramRepo_SendMessageAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *client.SendMessageAlbumRequest
		if args[0] != nil {
			arg0 = args[0].(*client.SendMessageAlbumRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_SendMessageAlbum_Call) Return(messages *client.Messages, err error) *TelegramRepo_SendMessageAlbum_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *TelegramRepo_SendMessageAlbum_Call) RunAndReturn(run func(sendMessageAlbumRequest *client.SendMessageAlbumRequest) (*client.Messages, error)) *TelegramRepo_SendMessageAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// Updates provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) Updates() <-chan client.Type {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Updates")
	}

	var r0 <-chan client.Type
	if returnFunc, ok := ret.Get(0).(func() <-chan client.Type); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan client.Type)
		}
	}
	return r0
}

// TelegramRepo_Updates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Updates'
type TelegramRepo_Updates_Call struct {
	*mock.Call
}

// Updates is a helper method to define mock.On call
func (_e *TelegramRepo_Expecter) Updates() *TelegramRepo_Updates_Call {
	return &TelegramRepo_Updates_Call{Call: _e.mock.On("Updates")}
}

func (_c *TelegramRepo_Updates_Call) Run(run func()) *TelegramRepo_Updates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TelegramRepo_Updates_Call) Return(typeCh <-chan client.Type) *TelegramRepo_Updates_Call {
	_c.Call.Return(typeCh)
	return _c
}

func (_c *TelegramRepo_Updates_Call) RunAndReturn(run func() <-chan client.Type) *TelegramRepo_Updates_Call {
	_c.Call.Return(run)
	return _c
}
