// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/pure-golang/budva-claude/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTelegramRepo creates a new instance of TelegramRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramRepo {
	mock := &TelegramRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TelegramRepo is an autogenerated mock type for the telegramRepo type
type TelegramRepo struct {
	mock.Mock
}

type TelegramRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramRepo) EXPECT() *TelegramRepo_Expecter {
	return &TelegramRepo_Expecter{mock: &_m.Mock}
}

// AuthStates provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) AuthStates() <-chan domain.AuthStateEvent {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthStates")
	}

	var r0 <-chan domain.AuthStateEvent
	if returnFunc, ok := ret.Get(0).(func() <-chan domain.AuthStateEvent); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan domain.AuthStateEvent)
		}
	}
	return r0
}

// TelegramRepo_AuthStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthStates'
type TelegramRepo_AuthStates_Call struct {
	*mock.Call
}

// AuthStates is a helper method to define mock.On call
func (_e *TelegramRepo_Expecter) AuthStates() *TelegramRepo_AuthStates_Call {
	return &TelegramRepo_AuthStates_Call{Call: _e.mock.On("AuthStates")}
}

func (_c *TelegramRepo_AuthStates_Call) Run(run func()) *TelegramRepo_AuthStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TelegramRepo_AuthStates_Call) Return(authStateEventCh <-chan domain.AuthStateEvent) *TelegramRepo_AuthStates_Call {
	_c.Call.Return(authStateEventCh)
	return _c
}

func (_c *TelegramRepo_AuthStates_Call) RunAndReturn(run func() <-chan domain.AuthStateEvent) *TelegramRepo_AuthStates_Call {
	_c.Call.Return(run)
	return _c
}

// CleanUp provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) CleanUp() {
	_mock.Called()
	return
}

// TelegramRepo_CleanUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanUp'
type TelegramRepo_CleanUp_Call struct {
	*mock.Call
}

// CleanUp is a helper method to define mock.On call
func (_e *TelegramRepo_Expecter) CleanUp() *TelegramRepo_CleanUp_Call {
	return &TelegramRepo_CleanUp_Call{Call: _e.mock.On("CleanUp")}
}

func (_c *TelegramRepo_CleanUp_Call) Run(run func()) *TelegramRepo_CleanUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TelegramRepo_CleanUp_Call) Return() *TelegramRepo_CleanUp_Call {
	_c.Call.Return()
	return _c
}

func (_c *TelegramRepo_CleanUp_Call) RunAndReturn(run func()) *TelegramRepo_CleanUp_Call {
	_c.Run(run)
	return _c
}

// LogOut provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) LogOut(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LogOut")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TelegramRepo_LogOut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogOut'
type TelegramRepo_LogOut_Call struct {
	*mock.Call
}

// LogOut is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TelegramRepo_Expecter) LogOut(ctx interface{}) *TelegramRepo_LogOut_Call {
	return &TelegramRepo_LogOut_Call{Call: _e.mock.On("LogOut", ctx)}
}

func (_c *TelegramRepo_LogOut_Call) Run(run func(ctx context.Context)) *TelegramRepo_LogOut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_LogOut_Call) Return(err error) *TelegramRepo_LogOut_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TelegramRepo_LogOut_Call) RunAndReturn(run func(ctx context.Context) error) *TelegramRepo_LogOut_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitCode provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) SubmitCode(ctx context.Context, code string) error {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for SubmitCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TelegramRepo_SubmitCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitCode'
type TelegramRepo_SubmitCode_Call struct {
	*mock.Call
}

// SubmitCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *TelegramRepo_Expecter) SubmitCode(ctx interface{}, code interface{}) *TelegramRepo_SubmitCode_Call {
	return &TelegramRepo_SubmitCode_Call{Call: _e.mock.On("SubmitCode", ctx, code)}
}

func (_c *TelegramRepo_SubmitCode_Call) Run(run func(ctx context.Context, code string)) *TelegramRepo_SubmitCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TelegramRepo_SubmitCode_Call) Return(err error) *TelegramRepo_SubmitCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TelegramRepo_SubmitCode_Call) RunAndReturn(run func(ctx context.Context, code string) error) *TelegramRepo_SubmitCode_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitPassword provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) SubmitPassword(ctx context.Context, password string) error {
	ret := _mock.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for SubmitPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TelegramRepo_SubmitPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitPassword'
type TelegramRepo_SubmitPassword_Call struct {
	*mock.Call
}

// SubmitPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
func (_e *TelegramRepo_Expecter) SubmitPassword(ctx interface{}, password interface{}) *TelegramRepo_SubmitPassword_Call {
	return &TelegramRepo_SubmitPassword_Call{Call: _e.mock.On("SubmitPassword", ctx, password)}
}

func (_c *TelegramRepo_SubmitPassword_Call) Run(run func(ctx context.Context, password string)) *TelegramRepo_SubmitPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TelegramRepo_SubmitPassword_Call) Return(err error) *TelegramRepo_SubmitPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TelegramRepo_SubmitPassword_Call) RunAndReturn(run func(ctx context.Context, password string) error) *TelegramRepo_SubmitPassword_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitPhone provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) SubmitPhone(ctx context.Context, phone string) error {
	ret := _mock.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for SubmitPhone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, phone)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TelegramRepo_SubmitPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitPhone'
type TelegramRepo_SubmitPhone_Call struct {
	*mock.Call
}

// SubmitPhone is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *TelegramRepo_Expecter) SubmitPhone(ctx interface{}, phone interface{}) *TelegramRepo_SubmitPhone_Call {
	return &TelegramRepo_SubmitPhone_Call{Call: _e.mock.On("SubmitPhone", ctx, phone)}
}

func (_c *TelegramRepo_SubmitPhone_Call) Run(run func(ctx context.Context, phone string)) *TelegramRepo_SubmitPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TelegramRepo_SubmitPhone_Call) Return(err error) *TelegramRepo_SubmitPhone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TelegramRepo_SubmitPhone_Call) RunAndReturn(run func(ctx context.Context, phone string) error) *TelegramRepo_SubmitPhone_Call {
	_c.Call.Return(run)
	return _c
}
