// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/pure-golang/budva-claude/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTelegramRepo creates a new instance of TelegramRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramRepo {
	mock := &TelegramRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TelegramRepo is an autogenerated mock type for the telegramRepo type
type TelegramRepo struct {
	mock.Mock
}

type TelegramRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramRepo) EXPECT() *TelegramRepo_Expecter {
	return &TelegramRepo_Expecter{mock: &_m.Mock}
}

// DeleteMessages provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) DeleteMessages(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID, revoke bool) error {
	ret := _mock.Called(ctx, chatID, messageIDs, revoke)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, []domain.MessageID, bool) error); ok {
		r0 = returnFunc(ctx, chatID, messageIDs, revoke)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TelegramRepo_DeleteMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessages'
type TelegramRepo_DeleteMessages_Call struct {
	*mock.Call
}

// DeleteMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageIDs []domain.MessageID
//   - revoke bool
func (_e *TelegramRepo_Expecter) DeleteMessages(ctx interface{}, chatID interface{}, messageIDs interface{}, revoke interface{}) *TelegramRepo_DeleteMessages_Call {
	return &TelegramRepo_DeleteMessages_Call{Call: _e.mock.On("DeleteMessages", ctx, chatID, messageIDs, revoke)}
}

func (_c *TelegramRepo_DeleteMessages_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID, revoke bool)) *TelegramRepo_DeleteMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 []domain.MessageID
		if args[2] != nil {
			arg2 = args[2].([]domain.MessageID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TelegramRepo_DeleteMessages_Call) Return(err error) *TelegramRepo_DeleteMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TelegramRepo_DeleteMessages_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID, revoke bool) error) *TelegramRepo_DeleteMessages_Call {
	_c.Call.Return(run)
	return _c
}

// EditMessageText provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) EditMessageText(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, text *domain.FormattedText) error {
	ret := _mock.Called(ctx, chatID, messageID, text)

	if len(ret) == 0 {
		panic("no return value specified for EditMessageText")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID, *domain.FormattedText) error); ok {
		r0 = returnFunc(ctx, chatID, messageID, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TelegramRepo_EditMessageText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditMessageText'
type TelegramRepo_EditMessageText_Call struct {
	*mock.Call
}

// EditMessageText is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageID domain.MessageID
//   - text *domain.FormattedText
func (_e *TelegramRepo_Expecter) EditMessageText(ctx interface{}, chatID interface{}, messageID interface{}, text interface{}) *TelegramRepo_EditMessageText_Call {
	return &TelegramRepo_EditMessageText_Call{Call: _e.mock.On("EditMessageText", ctx, chatID, messageID, text)}
}

func (_c *TelegramRepo_EditMessageText_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, text *domain.FormattedText)) *TelegramRepo_EditMessageText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		var arg3 *domain.FormattedText
		if args[3] != nil {
			arg3 = args[3].(*domain.FormattedText)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TelegramRepo_EditMessageText_Call) Return(err error) *TelegramRepo_EditMessageText_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TelegramRepo_EditMessageText_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, text *domain.FormattedText) error) *TelegramRepo_EditMessageText_Call {
	_c.Call.Return(run)
	return _c
}

// ForwardMessages provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) ForwardMessages(ctx context.Context, fromChatID domain.ChatID, toChatID domain.ChatID, messageIDs []domain.MessageID) ([]domain.MessageID, error) {
	ret := _mock.Called(ctx, fromChatID, toChatID, messageIDs)

	if len(ret) == 0 {
		panic("no return value specified for ForwardMessages")
	}

	var r0 []domain.MessageID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.ChatID, []domain.MessageID) ([]domain.MessageID, error)); ok {
		return returnFunc(ctx, fromChatID, toChatID, messageIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.ChatID, []domain.MessageID) []domain.MessageID); ok {
		r0 = returnFunc(ctx, fromChatID, toChatID, messageIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MessageID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.ChatID, []domain.MessageID) error); ok {
		r1 = returnFunc(ctx, fromChatID, toChatID, messageIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_ForwardMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForwardMessages'
type TelegramRepo_ForwardMessages_Call struct {
	*mock.Call
}

// ForwardMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - fromChatID domain.ChatID
//   - toChatID domain.ChatID
//   - messageIDs []domain.MessageID
func (_e *TelegramRepo_Expecter) ForwardMessages(ctx interface{}, fromChatID interface{}, toChatID interface{}, messageIDs interface{}) *TelegramRepo_ForwardMessages_Call {
	return &TelegramRepo_ForwardMessages_Call{Call: _e.mock.On("ForwardMessages", ctx, fromChatID, toChatID, messageIDs)}
}

func (_c *TelegramRepo_ForwardMessages_Call) Run(run func(ctx context.Context, fromChatID domain.ChatID, toChatID domain.ChatID, messageIDs []domain.MessageID)) *TelegramRepo_ForwardMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.ChatID
		if args[2] != nil {
			arg2 = args[2].(domain.ChatID)
		}
		var arg3 []domain.MessageID
		if args[3] != nil {
			arg3 = args[3].([]domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TelegramRepo_ForwardMessages_Call) Return(vs []domain.MessageID, err error) *TelegramRepo_ForwardMessages_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *TelegramRepo_ForwardMessages_Call) RunAndReturn(run func(ctx context.Context, fromChatID domain.ChatID, toChatID domain.ChatID, messageIDs []domain.MessageID) ([]domain.MessageID, error)) *TelegramRepo_ForwardMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatHistory provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetChatHistory(ctx context.Context, chatID domain.ChatID, fromMessageID domain.MessageID, offset int32, limit int32) ([]*domain.Message, error) {
	ret := _mock.Called(ctx, chatID, fromMessageID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetChatHistory")
	}

	var r0 []*domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID, int32, int32) ([]*domain.Message, error)); ok {
		return returnFunc(ctx, chatID, fromMessageID, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID, int32, int32) []*domain.Message); ok {
		r0 = returnFunc(ctx, chatID, fromMessageID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.MessageID, int32, int32) error); ok {
		r1 = returnFunc(ctx, chatID, fromMessageID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetChatHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatHistory'
type TelegramRepo_GetChatHistory_Call struct {
	*mock.Call
}

// GetChatHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - fromMessageID domain.MessageID
//   - offset int32
//   - limit int32
func (_e *TelegramRepo_Expecter) GetChatHistory(ctx interface{}, chatID interface{}, fromMessageID interface{}, offset interface{}, limit interface{}) *TelegramRepo_GetChatHistory_Call {
	return &TelegramRepo_GetChatHistory_Call{Call: _e.mock.On("GetChatHistory", ctx, chatID, fromMessageID, offset, limit)}
}

func (_c *TelegramRepo_GetChatHistory_Call) Run(run func(ctx context.Context, chatID domain.ChatID, fromMessageID domain.MessageID, offset int32, limit int32)) *TelegramRepo_GetChatHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		var arg4 int32
		if args[4] != nil {
			arg4 = args[4].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetChatHistory_Call) Return(messages []*domain.Message, err error) *TelegramRepo_GetChatHistory_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *TelegramRepo_GetChatHistory_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, fromMessageID domain.MessageID, offset int32, limit int32) ([]*domain.Message, error)) *TelegramRepo_GetChatHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetMe provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetMe(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type TelegramRepo_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TelegramRepo_Expecter) GetMe(ctx interface{}) *TelegramRepo_GetMe_Call {
	return &TelegramRepo_GetMe_Call{Call: _e.mock.On("GetMe", ctx)}
}

func (_c *TelegramRepo_GetMe_Call) Run(run func(ctx context.Context)) *TelegramRepo_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetMe_Call) Return(n int64, err error) *TelegramRepo_GetMe_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *TelegramRepo_GetMe_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *TelegramRepo_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessage provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetMessage(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) (*domain.Message, error) {
	ret := _mock.Called(ctx, chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 *domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID) (*domain.Message, error)); ok {
		return returnFunc(ctx, chatID, messageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID) *domain.Message); ok {
		r0 = returnFunc(ctx, chatID, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.MessageID) error); ok {
		r1 = returnFunc(ctx, chatID, messageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessage'
type TelegramRepo_GetMessage_Call struct {
	*mock.Call
}

// GetMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageID domain.MessageID
func (_e *TelegramRepo_Expecter) GetMessage(ctx interface{}, chatID interface{}, messageID interface{}) *TelegramRepo_GetMessage_Call {
	return &TelegramRepo_GetMessage_Call{Call: _e.mock.On("GetMessage", ctx, chatID, messageID)}
}

func (_c *TelegramRepo_GetMessage_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID)) *TelegramRepo_GetMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetMessage_Call) Return(message *domain.Message, err error) *TelegramRepo_GetMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *TelegramRepo_GetMessage_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) (*domain.Message, error)) *TelegramRepo_GetMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageLink provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetMessageLink(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, forAlbum bool) (string, error) {
	ret := _mock.Called(ctx, chatID, messageID, forAlbum)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageLink")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID, bool) (string, error)); ok {
		return returnFunc(ctx, chatID, messageID, forAlbum)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID, bool) string); ok {
		r0 = returnFunc(ctx, chatID, messageID, forAlbum)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.MessageID, bool) error); ok {
		r1 = returnFunc(ctx, chatID, messageID, forAlbum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetMessageLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageLink'
type TelegramRepo_GetMessageLink_Call struct {
	*mock.Call
}

// GetMessageLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageID domain.MessageID
//   - forAlbum bool
func (_e *TelegramRepo_Expecter) GetMessageLink(ctx interface{}, chatID interface{}, messageID interface{}, forAlbum interface{}) *TelegramRepo_GetMessageLink_Call {
	return &TelegramRepo_GetMessageLink_Call{Call: _e.mock.On("GetMessageLink", ctx, chatID, messageID, forAlbum)}
}

func (_c *TelegramRepo_GetMessageLink_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, forAlbum bool)) *TelegramRepo_GetMessageLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetMessageLink_Call) Return(s string, err error) *TelegramRepo_GetMessageLink_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TelegramRepo_GetMessageLink_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, forAlbum bool) (string, error)) *TelegramRepo_GetMessageLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageLinkInfo provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetMessageLinkInfo(ctx context.Context, url string) (*domain.MessageLinkInfo, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageLinkInfo")
	}

	var r0 *domain.MessageLinkInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.MessageLinkInfo, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.MessageLinkInfo); ok {
		r0 = returnFunc(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MessageLinkInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetMessageLinkInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageLinkInfo'
type TelegramRepo_GetMessageLinkInfo_Call struct {
	*mock.Call
}

// GetMessageLinkInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *TelegramRepo_Expecter) GetMessageLinkInfo(ctx interface{}, url interface{}) *TelegramRepo_GetMessageLinkInfo_Call {
	return &TelegramRepo_GetMessageLinkInfo_Call{Call: _e.mock.On("GetMessageLinkInfo", ctx, url)}
}

func (_c *TelegramRepo_GetMessageLinkInfo_Call) Run(run func(ctx context.Context, url string)) *TelegramRepo_GetMessageLinkInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetMessageLinkInfo_Call) Return(messageLinkInfo *domain.MessageLinkInfo, err error) *TelegramRepo_GetMessageLinkInfo_Call {
	_c.Call.Return(messageLinkInfo, err)
	return _c
}

func (_c *TelegramRepo_GetMessageLinkInfo_Call) RunAndReturn(run func(ctx context.Context, url string) (*domain.MessageLinkInfo, error)) *TelegramRepo_GetMessageLinkInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetMessages(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID) ([]*domain.Message, error) {
	ret := _mock.Called(ctx, chatID, messageIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []*domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, []domain.MessageID) ([]*domain.Message, error)); ok {
		return returnFunc(ctx, chatID, messageIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, []domain.MessageID) []*domain.Message); ok {
		r0 = returnFunc(ctx, chatID, messageIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, []domain.MessageID) error); ok {
		r1 = returnFunc(ctx, chatID, messageIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type TelegramRepo_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageIDs []domain.MessageID
func (_e *TelegramRepo_Expecter) GetMessages(ctx interface{}, chatID interface{}, messageIDs interface{}) *TelegramRepo_GetMessages_Call {
	return &TelegramRepo_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx, chatID, messageIDs)}
}

func (_c *TelegramRepo_GetMessages_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID)) *TelegramRepo_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 []domain.MessageID
		if args[2] != nil {
			arg2 = args[2].([]domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetMessages_Call) Return(messages []*domain.Message, err error) *TelegramRepo_GetMessages_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *TelegramRepo_GetMessages_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID) ([]*domain.Message, error)) *TelegramRepo_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetOption provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetOption(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOption")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOption'
type TelegramRepo_GetOption_Call struct {
	*mock.Call
}

// GetOption is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *TelegramRepo_Expecter) GetOption(ctx interface{}, name interface{}) *TelegramRepo_GetOption_Call {
	return &TelegramRepo_GetOption_Call{Call: _e.mock.On("GetOption", ctx, name)}
}

func (_c *TelegramRepo_GetOption_Call) Run(run func(ctx context.Context, name string)) *TelegramRepo_GetOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetOption_Call) Return(s string, err error) *TelegramRepo_GetOption_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TelegramRepo_GetOption_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *TelegramRepo_GetOption_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) SendMessage(ctx context.Context, chatID domain.ChatID, content domain.InputMessageContent) (domain.MessageID, error) {
	ret := _mock.Called(ctx, chatID, content)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 domain.MessageID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.InputMessageContent) (domain.MessageID, error)); ok {
		return returnFunc(ctx, chatID, content)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.InputMessageContent) domain.MessageID); ok {
		r0 = returnFunc(ctx, chatID, content)
	} else {
		r0 = ret.Get(0).(domain.MessageID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.InputMessageContent) error); ok {
		r1 = returnFunc(ctx, chatID, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type TelegramRepo_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - content domain.InputMessageContent
func (_e *TelegramRepo_Expecter) SendMessage(ctx interface{}, chatID interface{}, content interface{}) *TelegramRepo_SendMessage_Call {
	return &TelegramRepo_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, chatID, content)}
}

func (_c *TelegramRepo_SendMessage_Call) Run(run func(ctx context.Context, chatID domain.ChatID, content domain.InputMessageContent)) *TelegramRepo_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.InputMessageContent
		if args[2] != nil {
			arg2 = args[2].(domain.InputMessageContent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TelegramRepo_SendMessage_Call) Return(v domain.MessageID, err error) *TelegramRepo_SendMessage_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *TelegramRepo_SendMessage_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, content domain.InputMessageContent) (domain.MessageID, error)) *TelegramRepo_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessageAlbum provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) SendMessageAlbum(ctx context.Context, chatID domain.ChatID, contents []domain.InputMessageContent) ([]domain.MessageID, error) {
	ret := _mock.Called(ctx, chatID, contents)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageAlbum")
	}

	var r0 []domain.MessageID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, []domain.InputMessageContent) ([]domain.MessageID, error)); ok {
		return returnFunc(ctx, chatID, contents)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, []domain.InputMessageContent) []domain.MessageID); ok {
		r0 = returnFunc(ctx, chatID, contents)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MessageID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, []domain.InputMessageContent) error); ok {
		r1 = returnFunc(ctx, chatID, contents)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_SendMessageAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageAlbum'
type TelegramRepo_SendMessageAlbum_Call struct {
	*mock.Call
}

// SendMessageAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - contents []domain.InputMessageContent
func (_e *TelegramRepo_Expecter) SendMessageAlbum(ctx interface{}, chatID interface{}, contents interface{}) *TelegramRepo_SendMessageAlbum_Call {
	return &TelegramRepo_SendMessageAlbum_Call{Call: _e.mock.On("SendMessageAlbum", ctx, chatID, contents)}
}

func (_c *TelegramRepo_SendMessageAlbum_Call) Run(run func(ctx context.Context, chatID domain.ChatID, contents []domain.InputMessageContent)) *TelegramRepo_SendMessageAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 []domain.InputMessageContent
		if args[2] != nil {
			arg2 = args[2].([]domain.InputMessageContent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TelegramRepo_SendMessageAlbum_Call) Return(vs []domain.MessageID, err error) *TelegramRepo_SendMessageAlbum_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *TelegramRepo_SendMessageAlbum_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, contents []domain.InputMessageContent) ([]domain.MessageID, error)) *TelegramRepo_SendMessageAlbum_Call {
	_c.Call.Return(run)
	return _c
}
