// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/pure-golang/budva-claude/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTelegramGateway creates a new instance of TelegramGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramGateway {
	mock := &TelegramGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TelegramGateway is an autogenerated mock type for the telegramGateway type
type TelegramGateway struct {
	mock.Mock
}

type TelegramGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramGateway) EXPECT() *TelegramGateway_Expecter {
	return &TelegramGateway_Expecter{mock: &_m.Mock}
}

// DeleteMessages provides a mock function for the type TelegramGateway
func (_mock *TelegramGateway) DeleteMessages(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID, revoke bool) error {
	ret := _mock.Called(ctx, chatID, messageIDs, revoke)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, []domain.MessageID, bool) error); ok {
		r0 = returnFunc(ctx, chatID, messageIDs, revoke)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TelegramGateway_DeleteMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessages'
type TelegramGateway_DeleteMessages_Call struct {
	*mock.Call
}

// DeleteMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageIDs []domain.MessageID
//   - revoke bool
func (_e *TelegramGateway_Expecter) DeleteMessages(ctx interface{}, chatID interface{}, messageIDs interface{}, revoke interface{}) *TelegramGateway_DeleteMessages_Call {
	return &TelegramGateway_DeleteMessages_Call{Call: _e.mock.On("DeleteMessages", ctx, chatID, messageIDs, revoke)}
}

func (_c *TelegramGateway_DeleteMessages_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID, revoke bool)) *TelegramGateway_DeleteMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 []domain.MessageID
		if args[2] != nil {
			arg2 = args[2].([]domain.MessageID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TelegramGateway_DeleteMessages_Call) Return(err error) *TelegramGateway_DeleteMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TelegramGateway_DeleteMessages_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID, revoke bool) error) *TelegramGateway_DeleteMessages_Call {
	_c.Call.Return(run)
	return _c
}

// EditMessageText provides a mock function for the type TelegramGateway
func (_mock *TelegramGateway) EditMessageText(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, text *domain.FormattedText) error {
	ret := _mock.Called(ctx, chatID, messageID, text)

	if len(ret) == 0 {
		panic("no return value specified for EditMessageText")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID, *domain.FormattedText) error); ok {
		r0 = returnFunc(ctx, chatID, messageID, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TelegramGateway_EditMessageText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditMessageText'
type TelegramGateway_EditMessageText_Call struct {
	*mock.Call
}

// EditMessageText is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageID domain.MessageID
//   - text *domain.FormattedText
func (_e *TelegramGateway_Expecter) EditMessageText(ctx interface{}, chatID interface{}, messageID interface{}, text interface{}) *TelegramGateway_EditMessageText_Call {
	return &TelegramGateway_EditMessageText_Call{Call: _e.mock.On("EditMessageText", ctx, chatID, messageID, text)}
}

func (_c *TelegramGateway_EditMessageText_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, text *domain.FormattedText)) *TelegramGateway_EditMessageText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		var arg3 *domain.FormattedText
		if args[3] != nil {
			arg3 = args[3].(*domain.FormattedText)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TelegramGateway_EditMessageText_Call) Return(err error) *TelegramGateway_EditMessageText_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TelegramGateway_EditMessageText_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, text *domain.FormattedText) error) *TelegramGateway_EditMessageText_Call {
	_c.Call.Return(run)
	return _c
}

// ForwardMessages provides a mock function for the type TelegramGateway
func (_mock *TelegramGateway) ForwardMessages(ctx context.Context, fromChatID domain.ChatID, toChatID domain.ChatID, messageIDs []domain.MessageID) ([]domain.MessageID, error) {
	ret := _mock.Called(ctx, fromChatID, toChatID, messageIDs)

	if len(ret) == 0 {
		panic("no return value specified for ForwardMessages")
	}

	var r0 []domain.MessageID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.ChatID, []domain.MessageID) ([]domain.MessageID, error)); ok {
		return returnFunc(ctx, fromChatID, toChatID, messageIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.ChatID, []domain.MessageID) []domain.MessageID); ok {
		r0 = returnFunc(ctx, fromChatID, toChatID, messageIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MessageID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.ChatID, []domain.MessageID) error); ok {
		r1 = returnFunc(ctx, fromChatID, toChatID, messageIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramGateway_ForwardMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForwardMessages'
type TelegramGateway_ForwardMessages_Call struct {
	*mock.Call
}

// ForwardMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - fromChatID domain.ChatID
//   - toChatID domain.ChatID
//   - messageIDs []domain.MessageID
func (_e *TelegramGateway_Expecter) ForwardMessages(ctx interface{}, fromChatID interface{}, toChatID interface{}, messageIDs interface{}) *TelegramGateway_ForwardMessages_Call {
	return &TelegramGateway_ForwardMessages_Call{Call: _e.mock.On("ForwardMessages", ctx, fromChatID, toChatID, messageIDs)}
}

func (_c *TelegramGateway_ForwardMessages_Call) Run(run func(ctx context.Context, fromChatID domain.ChatID, toChatID domain.ChatID, messageIDs []domain.MessageID)) *TelegramGateway_ForwardMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.ChatID
		if args[2] != nil {
			arg2 = args[2].(domain.ChatID)
		}
		var arg3 []domain.MessageID
		if args[3] != nil {
			arg3 = args[3].([]domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TelegramGateway_ForwardMessages_Call) Return(vs []domain.MessageID, err error) *TelegramGateway_ForwardMessages_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *TelegramGateway_ForwardMessages_Call) RunAndReturn(run func(ctx context.Context, fromChatID domain.ChatID, toChatID domain.ChatID, messageIDs []domain.MessageID) ([]domain.MessageID, error)) *TelegramGateway_ForwardMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatHistory provides a mock function for the type TelegramGateway
func (_mock *TelegramGateway) GetChatHistory(ctx context.Context, chatID domain.ChatID, fromMessageID domain.MessageID, offset int32, limit int32) ([]*domain.Message, error) {
	ret := _mock.Called(ctx, chatID, fromMessageID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetChatHistory")
	}

	var r0 []*domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID, int32, int32) ([]*domain.Message, error)); ok {
		return returnFunc(ctx, chatID, fromMessageID, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID, int32, int32) []*domain.Message); ok {
		r0 = returnFunc(ctx, chatID, fromMessageID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.MessageID, int32, int32) error); ok {
		r1 = returnFunc(ctx, chatID, fromMessageID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramGateway_GetChatHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatHistory'
type TelegramGateway_GetChatHistory_Call struct {
	*mock.Call
}

// GetChatHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - fromMessageID domain.MessageID
//   - offset int32
//   - limit int32
func (_e *TelegramGateway_Expecter) GetChatHistory(ctx interface{}, chatID interface{}, fromMessageID interface{}, offset interface{}, limit interface{}) *TelegramGateway_GetChatHistory_Call {
	return &TelegramGateway_GetChatHistory_Call{Call: _e.mock.On("GetChatHistory", ctx, chatID, fromMessageID, offset, limit)}
}

func (_c *TelegramGateway_GetChatHistory_Call) Run(run func(ctx context.Context, chatID domain.ChatID, fromMessageID domain.MessageID, offset int32, limit int32)) *TelegramGateway_GetChatHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		var arg4 int32
		if args[4] != nil {
			arg4 = args[4].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TelegramGateway_GetChatHistory_Call) Return(messages []*domain.Message, err error) *TelegramGateway_GetChatHistory_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *TelegramGateway_GetChatHistory_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, fromMessageID domain.MessageID, offset int32, limit int32) ([]*domain.Message, error)) *TelegramGateway_GetChatHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetMe provides a mock function for the type TelegramGateway
func (_mock *TelegramGateway) GetMe(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramGateway_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type TelegramGateway_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TelegramGateway_Expecter) GetMe(ctx interface{}) *TelegramGateway_GetMe_Call {
	return &TelegramGateway_GetMe_Call{Call: _e.mock.On("GetMe", ctx)}
}

func (_c *TelegramGateway_GetMe_Call) Run(run func(ctx context.Context)) *TelegramGateway_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramGateway_GetMe_Call) Return(n int64, err error) *TelegramGateway_GetMe_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *TelegramGateway_GetMe_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *TelegramGateway_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessage provides a mock function for the type TelegramGateway
func (_mock *TelegramGateway) GetMessage(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) (*domain.Message, error) {
	ret := _mock.Called(ctx, chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 *domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID) (*domain.Message, error)); ok {
		return returnFunc(ctx, chatID, messageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID) *domain.Message); ok {
		r0 = returnFunc(ctx, chatID, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.MessageID) error); ok {
		r1 = returnFunc(ctx, chatID, messageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramGateway_GetMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessage'
type TelegramGateway_GetMessage_Call struct {
	*mock.Call
}

// GetMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageID domain.MessageID
func (_e *TelegramGateway_Expecter) GetMessage(ctx interface{}, chatID interface{}, messageID interface{}) *TelegramGateway_GetMessage_Call {
	return &TelegramGateway_GetMessage_Call{Call: _e.mock.On("GetMessage", ctx, chatID, messageID)}
}

func (_c *TelegramGateway_GetMessage_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID)) *TelegramGateway_GetMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TelegramGateway_GetMessage_Call) Return(message *domain.Message, err error) *TelegramGateway_GetMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *TelegramGateway_GetMessage_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) (*domain.Message, error)) *TelegramGateway_GetMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageLink provides a mock function for the type TelegramGateway
func (_mock *TelegramGateway) GetMessageLink(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) (string, error) {
	ret := _mock.Called(ctx, chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageLink")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID) (string, error)); ok {
		return returnFunc(ctx, chatID, messageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID) string); ok {
		r0 = returnFunc(ctx, chatID, messageID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.MessageID) error); ok {
		r1 = returnFunc(ctx, chatID, messageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramGateway_GetMessageLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageLink'
type TelegramGateway_GetMessageLink_Call struct {
	*mock.Call
}

// GetMessageLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageID domain.MessageID
func (_e *TelegramGateway_Expecter) GetMessageLink(ctx interface{}, chatID interface{}, messageID interface{}) *TelegramGateway_GetMessageLink_Call {
	return &TelegramGateway_GetMessageLink_Call{Call: _e.mock.On("GetMessageLink", ctx, chatID, messageID)}
}

func (_c *TelegramGateway_GetMessageLink_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID)) *TelegramGateway_GetMessageLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TelegramGateway_GetMessageLink_Call) Return(s string, err error) *TelegramGateway_GetMessageLink_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TelegramGateway_GetMessageLink_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) (string, error)) *TelegramGateway_GetMessageLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageLinkInfo provides a mock function for the type TelegramGateway
func (_mock *TelegramGateway) GetMessageLinkInfo(ctx context.Context, url string) (*domain.MessageLinkInfo, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageLinkInfo")
	}

	var r0 *domain.MessageLinkInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.MessageLinkInfo, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.MessageLinkInfo); ok {
		r0 = returnFunc(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MessageLinkInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramGateway_GetMessageLinkInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageLinkInfo'
type TelegramGateway_GetMessageLinkInfo_Call struct {
	*mock.Call
}

// GetMessageLinkInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *TelegramGateway_Expecter) GetMessageLinkInfo(ctx interface{}, url interface{}) *TelegramGateway_GetMessageLinkInfo_Call {
	return &TelegramGateway_GetMessageLinkInfo_Call{Call: _e.mock.On("GetMessageLinkInfo", ctx, url)}
}

func (_c *TelegramGateway_GetMessageLinkInfo_Call) Run(run func(ctx context.Context, url string)) *TelegramGateway_GetMessageLinkInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TelegramGateway_GetMessageLinkInfo_Call) Return(messageLinkInfo *domain.MessageLinkInfo, err error) *TelegramGateway_GetMessageLinkInfo_Call {
	_c.Call.Return(messageLinkInfo, err)
	return _c
}

func (_c *TelegramGateway_GetMessageLinkInfo_Call) RunAndReturn(run func(ctx context.Context, url string) (*domain.MessageLinkInfo, error)) *TelegramGateway_GetMessageLinkInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetOption provides a mock function for the type TelegramGateway
func (_mock *TelegramGateway) GetOption(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOption")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramGateway_GetOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOption'
type TelegramGateway_GetOption_Call struct {
	*mock.Call
}

// GetOption is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *TelegramGateway_Expecter) GetOption(ctx interface{}, name interface{}) *TelegramGateway_GetOption_Call {
	return &TelegramGateway_GetOption_Call{Call: _e.mock.On("GetOption", ctx, name)}
}

func (_c *TelegramGateway_GetOption_Call) Run(run func(ctx context.Context, name string)) *TelegramGateway_GetOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TelegramGateway_GetOption_Call) Return(s string, err error) *TelegramGateway_GetOption_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TelegramGateway_GetOption_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *TelegramGateway_GetOption_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type TelegramGateway
func (_mock *TelegramGateway) SendMessage(ctx context.Context, chatID domain.ChatID, content domain.InputMessageContent) (domain.MessageID, error) {
	ret := _mock.Called(ctx, chatID, content)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 domain.MessageID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.InputMessageContent) (domain.MessageID, error)); ok {
		return returnFunc(ctx, chatID, content)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.InputMessageContent) domain.MessageID); ok {
		r0 = returnFunc(ctx, chatID, content)
	} else {
		r0 = ret.Get(0).(domain.MessageID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.InputMessageContent) error); ok {
		r1 = returnFunc(ctx, chatID, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramGateway_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type TelegramGateway_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - content domain.InputMessageContent
func (_e *TelegramGateway_Expecter) SendMessage(ctx interface{}, chatID interface{}, content interface{}) *TelegramGateway_SendMessage_Call {
	return &TelegramGateway_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, chatID, content)}
}

func (_c *TelegramGateway_SendMessage_Call) Run(run func(ctx context.Context, chatID domain.ChatID, content domain.InputMessageContent)) *TelegramGateway_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.InputMessageContent
		if args[2] != nil {
			arg2 = args[2].(domain.InputMessageContent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TelegramGateway_SendMessage_Call) Return(v domain.MessageID, err error) *TelegramGateway_SendMessage_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *TelegramGateway_SendMessage_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, content domain.InputMessageContent) (domain.MessageID, error)) *TelegramGateway_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessageAlbum provides a mock function for the type TelegramGateway
func (_mock *TelegramGateway) SendMessageAlbum(ctx context.Context, chatID domain.ChatID, contents []domain.InputMessageContent) ([]domain.MessageID, error) {
	ret := _mock.Called(ctx, chatID, contents)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageAlbum")
	}

	var r0 []domain.MessageID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, []domain.InputMessageContent) ([]domain.MessageID, error)); ok {
		return returnFunc(ctx, chatID, contents)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, []domain.InputMessageContent) []domain.MessageID); ok {
		r0 = returnFunc(ctx, chatID, contents)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MessageID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, []domain.InputMessageContent) error); ok {
		r1 = returnFunc(ctx, chatID, contents)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramGateway_SendMessageAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageAlbum'
type TelegramGateway_SendMessageAlbum_Call struct {
	*mock.Call
}

// SendMessageAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - contents []domain.InputMessageContent
func (_e *TelegramGateway_Expecter) SendMessageAlbum(ctx interface{}, chatID interface{}, contents interface{}) *TelegramGateway_SendMessageAlbum_Call {
	return &TelegramGateway_SendMessageAlbum_Call{Call: _e.mock.On("SendMessageAlbum", ctx, chatID, contents)}
}

func (_c *TelegramGateway_SendMessageAlbum_Call) Run(run func(ctx context.Context, chatID domain.ChatID, contents []domain.InputMessageContent)) *TelegramGateway_SendMessageAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 []domain.InputMessageContent
		if args[2] != nil {
			arg2 = args[2].([]domain.InputMessageContent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TelegramGateway_SendMessageAlbum_Call) Return(vs []domain.MessageID, err error) *TelegramGateway_SendMessageAlbum_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *TelegramGateway_SendMessageAlbum_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, contents []domain.InputMessageContent) ([]domain.MessageID, error)) *TelegramGateway_SendMessageAlbum_Call {
	_c.Call.Return(run)
	return _c
}
