// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/pure-golang/budva-claude/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthService is an autogenerated mock type for the authService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// Extra provides a mock function for the type AuthService
func (_mock *AuthService) Extra() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Extra")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// AuthService_Extra_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extra'
type AuthService_Extra_Call struct {
	*mock.Call
}

// Extra is a helper method to define mock.On call
func (_e *AuthService_Expecter) Extra() *AuthService_Extra_Call {
	return &AuthService_Extra_Call{Call: _e.mock.On("Extra")}
}

func (_c *AuthService_Extra_Call) Run(run func()) *AuthService_Extra_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthService_Extra_Call) Return(v any) *AuthService_Extra_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *AuthService_Extra_Call) RunAndReturn(run func() any) *AuthService_Extra_Call {
	_c.Call.Return(run)
	return _c
}

// InputChan provides a mock function for the type AuthService
func (_mock *AuthService) InputChan() chan<- string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InputChan")
	}

	var r0 chan<- string
	if returnFunc, ok := ret.Get(0).(func() chan<- string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan<- string)
		}
	}
	return r0
}

// AuthService_InputChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InputChan'
type AuthService_InputChan_Call struct {
	*mock.Call
}

// InputChan is a helper method to define mock.On call
func (_e *AuthService_Expecter) InputChan() *AuthService_InputChan_Call {
	return &AuthService_InputChan_Call{Call: _e.mock.On("InputChan")}
}

func (_c *AuthService_InputChan_Call) Run(run func()) *AuthService_InputChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthService_InputChan_Call) Return(stringCh chan<- string) *AuthService_InputChan_Call {
	_c.Call.Return(stringCh)
	return _c
}

func (_c *AuthService_InputChan_Call) RunAndReturn(run func() chan<- string) *AuthService_InputChan_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function for the type AuthService
func (_mock *AuthService) State() domain.AuthorizationState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 domain.AuthorizationState
	if returnFunc, ok := ret.Get(0).(func() domain.AuthorizationState); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.AuthorizationState)
	}
	return r0
}

// AuthService_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type AuthService_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *AuthService_Expecter) State() *AuthService_State_Call {
	return &AuthService_State_Call{Call: _e.mock.On("State")}
}

func (_c *AuthService_State_Call) Run(run func()) *AuthService_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthService_State_Call) Return(authorizationState domain.AuthorizationState) *AuthService_State_Call {
	_c.Call.Return(authorizationState)
	return _c
}

func (_c *AuthService_State_Call) RunAndReturn(run func() domain.AuthorizationState) *AuthService_State_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type AuthService
func (_mock *AuthService) Subscribe(listener func(state domain.AuthorizationState, extra any)) {
	_mock.Called(listener)
	return
}

// AuthService_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type AuthService_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - listener func(state domain.AuthorizationState, extra any)
func (_e *AuthService_Expecter) Subscribe(listener interface{}) *AuthService_Subscribe_Call {
	return &AuthService_Subscribe_Call{Call: _e.mock.On("Subscribe", listener)}
}

func (_c *AuthService_Subscribe_Call) Run(run func(listener func(state domain.AuthorizationState, extra any))) *AuthService_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(state domain.AuthorizationState, extra any)
		if args[0] != nil {
			arg0 = args[0].(func(state domain.AuthorizationState, extra any))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthService_Subscribe_Call) Return() *AuthService_Subscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthService_Subscribe_Call) RunAndReturn(run func(listener func(state domain.AuthorizationState, extra any))) *AuthService_Subscribe_Call {
	_c.Run(run)
	return _c
}
