package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	graphql1 "github.com/pure-golang/budva-claude/internal/dto/graphql"
	"github.com/pure-golang/budva-claude/internal/transport/http/graph"
)

// Status is the resolver for the status field.
func (r *queryResolver) Status(ctx context.Context) (*graphql1.StatusResponse, error) {
	return r.statusService.GetStatus(ctx)
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
