// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/pure-golang/budva-claude/internal/dto/graphql"
	mock "github.com/stretchr/testify/mock"
)

// NewStatusProvider creates a new instance of StatusProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatusProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatusProvider {
	mock := &StatusProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StatusProvider is an autogenerated mock type for the statusProvider type
type StatusProvider struct {
	mock.Mock
}

type StatusProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *StatusProvider) EXPECT() *StatusProvider_Expecter {
	return &StatusProvider_Expecter{mock: &_m.Mock}
}

// GetStatus provides a mock function for the type StatusProvider
func (_mock *StatusProvider) GetStatus(ctx context.Context) (*graphql.StatusResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 *graphql.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*graphql.StatusResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *graphql.StatusResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graphql.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StatusProvider_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type StatusProvider_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StatusProvider_Expecter) GetStatus(ctx interface{}) *StatusProvider_GetStatus_Call {
	return &StatusProvider_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx)}
}

func (_c *StatusProvider_GetStatus_Call) Run(run func(ctx context.Context)) *StatusProvider_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StatusProvider_GetStatus_Call) Return(statusResponse *graphql.StatusResponse, err error) *StatusProvider_GetStatus_Call {
	_c.Call.Return(statusResponse, err)
	return _c
}

func (_c *StatusProvider_GetStatus_Call) RunAndReturn(run func(ctx context.Context) (*graphql.StatusResponse, error)) *StatusProvider_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}
