// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/pure-golang/budva-claude/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewStateRepo creates a new instance of StateRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateRepo {
	mock := &StateRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StateRepo is an autogenerated mock type for the stateRepo type
type StateRepo struct {
	mock.Mock
}

type StateRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *StateRepo) EXPECT() *StateRepo_Expecter {
	return &StateRepo_Expecter{mock: &_m.Mock}
}

// GetCopiedMessageIDs provides a mock function for the type StateRepo
func (_mock *StateRepo) GetCopiedMessageIDs(chatID domain.ChatID, messageID domain.MessageID) []string {
	ret := _mock.Called(chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetCopiedMessageIDs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, domain.MessageID) []string); ok {
		r0 = returnFunc(chatID, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// StateRepo_GetCopiedMessageIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCopiedMessageIDs'
type StateRepo_GetCopiedMessageIDs_Call struct {
	*mock.Call
}

// GetCopiedMessageIDs is a helper method to define mock.On call
//   - chatID domain.ChatID
//   - messageID domain.MessageID
func (_e *StateRepo_Expecter) GetCopiedMessageIDs(chatID interface{}, messageID interface{}) *StateRepo_GetCopiedMessageIDs_Call {
	return &StateRepo_GetCopiedMessageIDs_Call{Call: _e.mock.On("GetCopiedMessageIDs", chatID, messageID)}
}

func (_c *StateRepo_GetCopiedMessageIDs_Call) Run(run func(chatID domain.ChatID, messageID domain.MessageID)) *StateRepo_GetCopiedMessageIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 domain.MessageID
		if args[1] != nil {
			arg1 = args[1].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateRepo_GetCopiedMessageIDs_Call) Return(strings []string) *StateRepo_GetCopiedMessageIDs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *StateRepo_GetCopiedMessageIDs_Call) RunAndReturn(run func(chatID domain.ChatID, messageID domain.MessageID) []string) *StateRepo_GetCopiedMessageIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewMessageID provides a mock function for the type StateRepo
func (_mock *StateRepo) GetNewMessageID(chatID domain.ChatID, tmpMessageID domain.MessageID) domain.MessageID {
	ret := _mock.Called(chatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for GetNewMessageID")
	}

	var r0 domain.MessageID
	if returnFunc, ok := ret.Get(0).(func(domain.ChatID, domain.MessageID) domain.MessageID); ok {
		r0 = returnFunc(chatID, tmpMessageID)
	} else {
		r0 = ret.Get(0).(domain.MessageID)
	}
	return r0
}

// StateRepo_GetNewMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewMessageID'
type StateRepo_GetNewMessageID_Call struct {
	*mock.Call
}

// GetNewMessageID is a helper method to define mock.On call
//   - chatID domain.ChatID
//   - tmpMessageID domain.MessageID
func (_e *StateRepo_Expecter) GetNewMessageID(chatID interface{}, tmpMessageID interface{}) *StateRepo_GetNewMessageID_Call {
	return &StateRepo_GetNewMessageID_Call{Call: _e.mock.On("GetNewMessageID", chatID, tmpMessageID)}
}

func (_c *StateRepo_GetNewMessageID_Call) Run(run func(chatID domain.ChatID, tmpMessageID domain.MessageID)) *StateRepo_GetNewMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ChatID
		if args[0] != nil {
			arg0 = args[0].(domain.ChatID)
		}
		var arg1 domain.MessageID
		if args[1] != nil {
			arg1 = args[1].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateRepo_GetNewMessageID_Call) Return(v domain.MessageID) *StateRepo_GetNewMessageID_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *StateRepo_GetNewMessageID_Call) RunAndReturn(run func(chatID domain.ChatID, tmpMessageID domain.MessageID) domain.MessageID) *StateRepo_GetNewMessageID_Call {
	_c.Call.Return(run)
	return _c
}
