// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewStateRepo creates a new instance of StateRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateRepo {
	mock := &StateRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StateRepo is an autogenerated mock type for the stateRepo type
type StateRepo struct {
	mock.Mock
}

type StateRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *StateRepo) EXPECT() *StateRepo_Expecter {
	return &StateRepo_Expecter{mock: &_m.Mock}
}

// GetCopiedMessageIDs provides a mock function for the type StateRepo
func (_mock *StateRepo) GetCopiedMessageIDs(chatID int64, messageID int64) []string {
	ret := _mock.Called(chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetCopiedMessageIDs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(int64, int64) []string); ok {
		r0 = returnFunc(chatID, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// StateRepo_GetCopiedMessageIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCopiedMessageIDs'
type StateRepo_GetCopiedMessageIDs_Call struct {
	*mock.Call
}

// GetCopiedMessageIDs is a helper method to define mock.On call
//   - chatID int64
//   - messageID int64
func (_e *StateRepo_Expecter) GetCopiedMessageIDs(chatID interface{}, messageID interface{}) *StateRepo_GetCopiedMessageIDs_Call {
	return &StateRepo_GetCopiedMessageIDs_Call{Call: _e.mock.On("GetCopiedMessageIDs", chatID, messageID)}
}

func (_c *StateRepo_GetCopiedMessageIDs_Call) Run(run func(chatID int64, messageID int64)) *StateRepo_GetCopiedMessageIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateRepo_GetCopiedMessageIDs_Call) Return(strings []string) *StateRepo_GetCopiedMessageIDs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *StateRepo_GetCopiedMessageIDs_Call) RunAndReturn(run func(chatID int64, messageID int64) []string) *StateRepo_GetCopiedMessageIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewMessageID provides a mock function for the type StateRepo
func (_mock *StateRepo) GetNewMessageID(chatID int64, tmpMessageID int64) int64 {
	ret := _mock.Called(chatID, tmpMessageID)

	if len(ret) == 0 {
		panic("no return value specified for GetNewMessageID")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(int64, int64) int64); ok {
		r0 = returnFunc(chatID, tmpMessageID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// StateRepo_GetNewMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewMessageID'
type StateRepo_GetNewMessageID_Call struct {
	*mock.Call
}

// GetNewMessageID is a helper method to define mock.On call
//   - chatID int64
//   - tmpMessageID int64
func (_e *StateRepo_Expecter) GetNewMessageID(chatID interface{}, tmpMessageID interface{}) *StateRepo_GetNewMessageID_Call {
	return &StateRepo_GetNewMessageID_Call{Call: _e.mock.On("GetNewMessageID", chatID, tmpMessageID)}
}

func (_c *StateRepo_GetNewMessageID_Call) Run(run func(chatID int64, tmpMessageID int64)) *StateRepo_GetNewMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateRepo_GetNewMessageID_Call) Return(n int64) *StateRepo_GetNewMessageID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *StateRepo_GetNewMessageID_Call) RunAndReturn(run func(chatID int64, tmpMessageID int64) int64) *StateRepo_GetNewMessageID_Call {
	_c.Call.Return(run)
	return _c
}
