// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/zelenin/go-tdlib/client"
)

// NewTelegramRepo creates a new instance of TelegramRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramRepo {
	mock := &TelegramRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TelegramRepo is an autogenerated mock type for the telegramRepo type
type TelegramRepo struct {
	mock.Mock
}

type TelegramRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramRepo) EXPECT() *TelegramRepo_Expecter {
	return &TelegramRepo_Expecter{mock: &_m.Mock}
}

// GetCallbackQueryAnswer provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetCallbackQueryAnswer(getCallbackQueryAnswerRequest *client.GetCallbackQueryAnswerRequest) (*client.CallbackQueryAnswer, error) {
	ret := _mock.Called(getCallbackQueryAnswerRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetCallbackQueryAnswer")
	}

	var r0 *client.CallbackQueryAnswer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*client.GetCallbackQueryAnswerRequest) (*client.CallbackQueryAnswer, error)); ok {
		return returnFunc(getCallbackQueryAnswerRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*client.GetCallbackQueryAnswerRequest) *client.CallbackQueryAnswer); ok {
		r0 = returnFunc(getCallbackQueryAnswerRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.CallbackQueryAnswer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*client.GetCallbackQueryAnswerRequest) error); ok {
		r1 = returnFunc(getCallbackQueryAnswerRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetCallbackQueryAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCallbackQueryAnswer'
type TelegramRepo_GetCallbackQueryAnswer_Call struct {
	*mock.Call
}

// GetCallbackQueryAnswer is a helper method to define mock.On call
//   - getCallbackQueryAnswerRequest *client.GetCallbackQueryAnswerRequest
func (_e *TelegramRepo_Expecter) GetCallbackQueryAnswer(getCallbackQueryAnswerRequest interface{}) *TelegramRepo_GetCallbackQueryAnswer_Call {
	return &TelegramRepo_GetCallbackQueryAnswer_Call{Call: _e.mock.On("GetCallbackQueryAnswer", getCallbackQueryAnswerRequest)}
}

func (_c *TelegramRepo_GetCallbackQueryAnswer_Call) Run(run func(getCallbackQueryAnswerRequest *client.GetCallbackQueryAnswerRequest)) *TelegramRepo_GetCallbackQueryAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *client.GetCallbackQueryAnswerRequest
		if args[0] != nil {
			arg0 = args[0].(*client.GetCallbackQueryAnswerRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetCallbackQueryAnswer_Call) Return(callbackQueryAnswer *client.CallbackQueryAnswer, err error) *TelegramRepo_GetCallbackQueryAnswer_Call {
	_c.Call.Return(callbackQueryAnswer, err)
	return _c
}

func (_c *TelegramRepo_GetCallbackQueryAnswer_Call) RunAndReturn(run func(getCallbackQueryAnswerRequest *client.GetCallbackQueryAnswerRequest) (*client.CallbackQueryAnswer, error)) *TelegramRepo_GetCallbackQueryAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// GetChat provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetChat(getChatRequest *client.GetChatRequest) (*client.Chat, error) {
	ret := _mock.Called(getChatRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetChat")
	}

	var r0 *client.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*client.GetChatRequest) (*client.Chat, error)); ok {
		return returnFunc(getChatRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*client.GetChatRequest) *client.Chat); ok {
		r0 = returnFunc(getChatRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*client.GetChatRequest) error); ok {
		r1 = returnFunc(getChatRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChat'
type TelegramRepo_GetChat_Call struct {
	*mock.Call
}

// GetChat is a helper method to define mock.On call
//   - getChatRequest *client.GetChatRequest
func (_e *TelegramRepo_Expecter) GetChat(getChatRequest interface{}) *TelegramRepo_GetChat_Call {
	return &TelegramRepo_GetChat_Call{Call: _e.mock.On("GetChat", getChatRequest)}
}

func (_c *TelegramRepo_GetChat_Call) Run(run func(getChatRequest *client.GetChatRequest)) *TelegramRepo_GetChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *client.GetChatRequest
		if args[0] != nil {
			arg0 = args[0].(*client.GetChatRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetChat_Call) Return(chat *client.Chat, err error) *TelegramRepo_GetChat_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *TelegramRepo_GetChat_Call) RunAndReturn(run func(getChatRequest *client.GetChatRequest) (*client.Chat, error)) *TelegramRepo_GetChat_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageLink provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetMessageLink(getMessageLinkRequest *client.GetMessageLinkRequest) (*client.MessageLink, error) {
	ret := _mock.Called(getMessageLinkRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageLink")
	}

	var r0 *client.MessageLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*client.GetMessageLinkRequest) (*client.MessageLink, error)); ok {
		return returnFunc(getMessageLinkRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*client.GetMessageLinkRequest) *client.MessageLink); ok {
		r0 = returnFunc(getMessageLinkRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.MessageLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*client.GetMessageLinkRequest) error); ok {
		r1 = returnFunc(getMessageLinkRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetMessageLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageLink'
type TelegramRepo_GetMessageLink_Call struct {
	*mock.Call
}

// GetMessageLink is a helper method to define mock.On call
//   - getMessageLinkRequest *client.GetMessageLinkRequest
func (_e *TelegramRepo_Expecter) GetMessageLink(getMessageLinkRequest interface{}) *TelegramRepo_GetMessageLink_Call {
	return &TelegramRepo_GetMessageLink_Call{Call: _e.mock.On("GetMessageLink", getMessageLinkRequest)}
}

func (_c *TelegramRepo_GetMessageLink_Call) Run(run func(getMessageLinkRequest *client.GetMessageLinkRequest)) *TelegramRepo_GetMessageLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *client.GetMessageLinkRequest
		if args[0] != nil {
			arg0 = args[0].(*client.GetMessageLinkRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetMessageLink_Call) Return(messageLink *client.MessageLink, err error) *TelegramRepo_GetMessageLink_Call {
	_c.Call.Return(messageLink, err)
	return _c
}

func (_c *TelegramRepo_GetMessageLink_Call) RunAndReturn(run func(getMessageLinkRequest *client.GetMessageLinkRequest) (*client.MessageLink, error)) *TelegramRepo_GetMessageLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageLinkInfo provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetMessageLinkInfo(getMessageLinkInfoRequest *client.GetMessageLinkInfoRequest) (*client.MessageLinkInfo, error) {
	ret := _mock.Called(getMessageLinkInfoRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageLinkInfo")
	}

	var r0 *client.MessageLinkInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*client.GetMessageLinkInfoRequest) (*client.MessageLinkInfo, error)); ok {
		return returnFunc(getMessageLinkInfoRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*client.GetMessageLinkInfoRequest) *client.MessageLinkInfo); ok {
		r0 = returnFunc(getMessageLinkInfoRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.MessageLinkInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*client.GetMessageLinkInfoRequest) error); ok {
		r1 = returnFunc(getMessageLinkInfoRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetMessageLinkInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageLinkInfo'
type TelegramRepo_GetMessageLinkInfo_Call struct {
	*mock.Call
}

// GetMessageLinkInfo is a helper method to define mock.On call
//   - getMessageLinkInfoRequest *client.GetMessageLinkInfoRequest
func (_e *TelegramRepo_Expecter) GetMessageLinkInfo(getMessageLinkInfoRequest interface{}) *TelegramRepo_GetMessageLinkInfo_Call {
	return &TelegramRepo_GetMessageLinkInfo_Call{Call: _e.mock.On("GetMessageLinkInfo", getMessageLinkInfoRequest)}
}

func (_c *TelegramRepo_GetMessageLinkInfo_Call) Run(run func(getMessageLinkInfoRequest *client.GetMessageLinkInfoRequest)) *TelegramRepo_GetMessageLinkInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *client.GetMessageLinkInfoRequest
		if args[0] != nil {
			arg0 = args[0].(*client.GetMessageLinkInfoRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetMessageLinkInfo_Call) Return(messageLinkInfo *client.MessageLinkInfo, err error) *TelegramRepo_GetMessageLinkInfo_Call {
	_c.Call.Return(messageLinkInfo, err)
	return _c
}

func (_c *TelegramRepo_GetMessageLinkInfo_Call) RunAndReturn(run func(getMessageLinkInfoRequest *client.GetMessageLinkInfoRequest) (*client.MessageLinkInfo, error)) *TelegramRepo_GetMessageLinkInfo_Call {
	_c.Call.Return(run)
	return _c
}

// TranslateText provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) TranslateText(translateTextRequest *client.TranslateTextRequest) (*client.FormattedText, error) {
	ret := _mock.Called(translateTextRequest)

	if len(ret) == 0 {
		panic("no return value specified for TranslateText")
	}

	var r0 *client.FormattedText
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*client.TranslateTextRequest) (*client.FormattedText, error)); ok {
		return returnFunc(translateTextRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*client.TranslateTextRequest) *client.FormattedText); ok {
		r0 = returnFunc(translateTextRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.FormattedText)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*client.TranslateTextRequest) error); ok {
		r1 = returnFunc(translateTextRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_TranslateText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranslateText'
type TelegramRepo_TranslateText_Call struct {
	*mock.Call
}

// TranslateText is a helper method to define mock.On call
//   - translateTextRequest *client.TranslateTextRequest
func (_e *TelegramRepo_Expecter) TranslateText(translateTextRequest interface{}) *TelegramRepo_TranslateText_Call {
	return &TelegramRepo_TranslateText_Call{Call: _e.mock.On("TranslateText", translateTextRequest)}
}

func (_c *TelegramRepo_TranslateText_Call) Run(run func(translateTextRequest *client.TranslateTextRequest)) *TelegramRepo_TranslateText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *client.TranslateTextRequest
		if args[0] != nil {
			arg0 = args[0].(*client.TranslateTextRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TelegramRepo_TranslateText_Call) Return(formattedText *client.FormattedText, err error) *TelegramRepo_TranslateText_Call {
	_c.Call.Return(formattedText, err)
	return _c
}

func (_c *TelegramRepo_TranslateText_Call) RunAndReturn(run func(translateTextRequest *client.TranslateTextRequest) (*client.FormattedText, error)) *TelegramRepo_TranslateText_Call {
	_c.Call.Return(run)
	return _c
}
