// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/pure-golang/budva-claude/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTelegramRepo creates a new instance of TelegramRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramRepo {
	mock := &TelegramRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TelegramRepo is an autogenerated mock type for the telegramRepo type
type TelegramRepo struct {
	mock.Mock
}

type TelegramRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramRepo) EXPECT() *TelegramRepo_Expecter {
	return &TelegramRepo_Expecter{mock: &_m.Mock}
}

// GetCallbackQueryAnswer provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetCallbackQueryAnswer(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, data []byte) (string, error) {
	ret := _mock.Called(ctx, chatID, messageID, data)

	if len(ret) == 0 {
		panic("no return value specified for GetCallbackQueryAnswer")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID, []byte) (string, error)); ok {
		return returnFunc(ctx, chatID, messageID, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID, []byte) string); ok {
		r0 = returnFunc(ctx, chatID, messageID, data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.MessageID, []byte) error); ok {
		r1 = returnFunc(ctx, chatID, messageID, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetCallbackQueryAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCallbackQueryAnswer'
type TelegramRepo_GetCallbackQueryAnswer_Call struct {
	*mock.Call
}

// GetCallbackQueryAnswer is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageID domain.MessageID
//   - data []byte
func (_e *TelegramRepo_Expecter) GetCallbackQueryAnswer(ctx interface{}, chatID interface{}, messageID interface{}, data interface{}) *TelegramRepo_GetCallbackQueryAnswer_Call {
	return &TelegramRepo_GetCallbackQueryAnswer_Call{Call: _e.mock.On("GetCallbackQueryAnswer", ctx, chatID, messageID, data)}
}

func (_c *TelegramRepo_GetCallbackQueryAnswer_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, data []byte)) *TelegramRepo_GetCallbackQueryAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetCallbackQueryAnswer_Call) Return(s string, err error) *TelegramRepo_GetCallbackQueryAnswer_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TelegramRepo_GetCallbackQueryAnswer_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, data []byte) (string, error)) *TelegramRepo_GetCallbackQueryAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatType provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetChatType(ctx context.Context, chatID domain.ChatID) (string, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetChatType")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID) (string, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID) string); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetChatType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatType'
type TelegramRepo_GetChatType_Call struct {
	*mock.Call
}

// GetChatType is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
func (_e *TelegramRepo_Expecter) GetChatType(ctx interface{}, chatID interface{}) *TelegramRepo_GetChatType_Call {
	return &TelegramRepo_GetChatType_Call{Call: _e.mock.On("GetChatType", ctx, chatID)}
}

func (_c *TelegramRepo_GetChatType_Call) Run(run func(ctx context.Context, chatID domain.ChatID)) *TelegramRepo_GetChatType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetChatType_Call) Return(s string, err error) *TelegramRepo_GetChatType_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TelegramRepo_GetChatType_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID) (string, error)) *TelegramRepo_GetChatType_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageLink provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetMessageLink(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) (string, error) {
	ret := _mock.Called(ctx, chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageLink")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID) (string, error)); ok {
		return returnFunc(ctx, chatID, messageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID) string); ok {
		r0 = returnFunc(ctx, chatID, messageID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.MessageID) error); ok {
		r1 = returnFunc(ctx, chatID, messageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetMessageLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageLink'
type TelegramRepo_GetMessageLink_Call struct {
	*mock.Call
}

// GetMessageLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageID domain.MessageID
func (_e *TelegramRepo_Expecter) GetMessageLink(ctx interface{}, chatID interface{}, messageID interface{}) *TelegramRepo_GetMessageLink_Call {
	return &TelegramRepo_GetMessageLink_Call{Call: _e.mock.On("GetMessageLink", ctx, chatID, messageID)}
}

func (_c *TelegramRepo_GetMessageLink_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID)) *TelegramRepo_GetMessageLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetMessageLink_Call) Return(s string, err error) *TelegramRepo_GetMessageLink_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TelegramRepo_GetMessageLink_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) (string, error)) *TelegramRepo_GetMessageLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageLinkInfo provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) GetMessageLinkInfo(ctx context.Context, url string) (*domain.MessageLinkInfo, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageLinkInfo")
	}

	var r0 *domain.MessageLinkInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.MessageLinkInfo, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.MessageLinkInfo); ok {
		r0 = returnFunc(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MessageLinkInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_GetMessageLinkInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageLinkInfo'
type TelegramRepo_GetMessageLinkInfo_Call struct {
	*mock.Call
}

// GetMessageLinkInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *TelegramRepo_Expecter) GetMessageLinkInfo(ctx interface{}, url interface{}) *TelegramRepo_GetMessageLinkInfo_Call {
	return &TelegramRepo_GetMessageLinkInfo_Call{Call: _e.mock.On("GetMessageLinkInfo", ctx, url)}
}

func (_c *TelegramRepo_GetMessageLinkInfo_Call) Run(run func(ctx context.Context, url string)) *TelegramRepo_GetMessageLinkInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TelegramRepo_GetMessageLinkInfo_Call) Return(messageLinkInfo *domain.MessageLinkInfo, err error) *TelegramRepo_GetMessageLinkInfo_Call {
	_c.Call.Return(messageLinkInfo, err)
	return _c
}

func (_c *TelegramRepo_GetMessageLinkInfo_Call) RunAndReturn(run func(ctx context.Context, url string) (*domain.MessageLinkInfo, error)) *TelegramRepo_GetMessageLinkInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ParseTextEntities provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) ParseTextEntities(ctx context.Context, text string) (*domain.FormattedText, error) {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for ParseTextEntities")
	}

	var r0 *domain.FormattedText
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.FormattedText, error)); ok {
		return returnFunc(ctx, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.FormattedText); ok {
		r0 = returnFunc(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FormattedText)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_ParseTextEntities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseTextEntities'
type TelegramRepo_ParseTextEntities_Call struct {
	*mock.Call
}

// ParseTextEntities is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *TelegramRepo_Expecter) ParseTextEntities(ctx interface{}, text interface{}) *TelegramRepo_ParseTextEntities_Call {
	return &TelegramRepo_ParseTextEntities_Call{Call: _e.mock.On("ParseTextEntities", ctx, text)}
}

func (_c *TelegramRepo_ParseTextEntities_Call) Run(run func(ctx context.Context, text string)) *TelegramRepo_ParseTextEntities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TelegramRepo_ParseTextEntities_Call) Return(formattedText *domain.FormattedText, err error) *TelegramRepo_ParseTextEntities_Call {
	_c.Call.Return(formattedText, err)
	return _c
}

func (_c *TelegramRepo_ParseTextEntities_Call) RunAndReturn(run func(ctx context.Context, text string) (*domain.FormattedText, error)) *TelegramRepo_ParseTextEntities_Call {
	_c.Call.Return(run)
	return _c
}

// TranslateText provides a mock function for the type TelegramRepo
func (_mock *TelegramRepo) TranslateText(ctx context.Context, text *domain.FormattedText, lang string) (*domain.FormattedText, error) {
	ret := _mock.Called(ctx, text, lang)

	if len(ret) == 0 {
		panic("no return value specified for TranslateText")
	}

	var r0 *domain.FormattedText
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.FormattedText, string) (*domain.FormattedText, error)); ok {
		return returnFunc(ctx, text, lang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.FormattedText, string) *domain.FormattedText); ok {
		r0 = returnFunc(ctx, text, lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FormattedText)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.FormattedText, string) error); ok {
		r1 = returnFunc(ctx, text, lang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TelegramRepo_TranslateText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranslateText'
type TelegramRepo_TranslateText_Call struct {
	*mock.Call
}

// TranslateText is a helper method to define mock.On call
//   - ctx context.Context
//   - text *domain.FormattedText
//   - lang string
func (_e *TelegramRepo_Expecter) TranslateText(ctx interface{}, text interface{}, lang interface{}) *TelegramRepo_TranslateText_Call {
	return &TelegramRepo_TranslateText_Call{Call: _e.mock.On("TranslateText", ctx, text, lang)}
}

func (_c *TelegramRepo_TranslateText_Call) Run(run func(ctx context.Context, text *domain.FormattedText, lang string)) *TelegramRepo_TranslateText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.FormattedText
		if args[1] != nil {
			arg1 = args[1].(*domain.FormattedText)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TelegramRepo_TranslateText_Call) Return(formattedText *domain.FormattedText, err error) *TelegramRepo_TranslateText_Call {
	_c.Call.Return(formattedText, err)
	return _c
}

func (_c *TelegramRepo_TranslateText_Call) RunAndReturn(run func(ctx context.Context, text *domain.FormattedText, lang string) (*domain.FormattedText, error)) *TelegramRepo_TranslateText_Call {
	_c.Call.Return(run)
	return _c
}
