// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/pure-golang/budva-claude/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewFacadeService creates a new instance of FacadeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFacadeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FacadeService {
	mock := &FacadeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FacadeService is an autogenerated mock type for the facadeService type
type FacadeService struct {
	mock.Mock
}

type FacadeService_Expecter struct {
	mock *mock.Mock
}

func (_m *FacadeService) EXPECT() *FacadeService_Expecter {
	return &FacadeService_Expecter{mock: &_m.Mock}
}

// DeleteMessages provides a mock function for the type FacadeService
func (_mock *FacadeService) DeleteMessages(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID) error {
	ret := _mock.Called(ctx, chatID, messageIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, []domain.MessageID) error); ok {
		r0 = returnFunc(ctx, chatID, messageIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FacadeService_DeleteMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessages'
type FacadeService_DeleteMessages_Call struct {
	*mock.Call
}

// DeleteMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageIDs []domain.MessageID
func (_e *FacadeService_Expecter) DeleteMessages(ctx interface{}, chatID interface{}, messageIDs interface{}) *FacadeService_DeleteMessages_Call {
	return &FacadeService_DeleteMessages_Call{Call: _e.mock.On("DeleteMessages", ctx, chatID, messageIDs)}
}

func (_c *FacadeService_DeleteMessages_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID)) *FacadeService_DeleteMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 []domain.MessageID
		if args[2] != nil {
			arg2 = args[2].([]domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FacadeService_DeleteMessages_Call) Return(err error) *FacadeService_DeleteMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FacadeService_DeleteMessages_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID) error) *FacadeService_DeleteMessages_Call {
	_c.Call.Return(run)
	return _c
}

// ForwardMessage provides a mock function for the type FacadeService
func (_mock *FacadeService) ForwardMessage(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) error {
	ret := _mock.Called(ctx, chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for ForwardMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID) error); ok {
		r0 = returnFunc(ctx, chatID, messageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FacadeService_ForwardMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForwardMessage'
type FacadeService_ForwardMessage_Call struct {
	*mock.Call
}

// ForwardMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageID domain.MessageID
func (_e *FacadeService_Expecter) ForwardMessage(ctx interface{}, chatID interface{}, messageID interface{}) *FacadeService_ForwardMessage_Call {
	return &FacadeService_ForwardMessage_Call{Call: _e.mock.On("ForwardMessage", ctx, chatID, messageID)}
}

func (_c *FacadeService_ForwardMessage_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID)) *FacadeService_ForwardMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FacadeService_ForwardMessage_Call) Return(err error) *FacadeService_ForwardMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FacadeService_ForwardMessage_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) error) *FacadeService_ForwardMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatHistory provides a mock function for the type FacadeService
func (_mock *FacadeService) GetChatHistory(ctx context.Context, chatID domain.ChatID, fromMessageID domain.MessageID, offset int32, limit int32) ([]*domain.Message, error) {
	ret := _mock.Called(ctx, chatID, fromMessageID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetChatHistory")
	}

	var r0 []*domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID, int32, int32) ([]*domain.Message, error)); ok {
		return returnFunc(ctx, chatID, fromMessageID, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID, int32, int32) []*domain.Message); ok {
		r0 = returnFunc(ctx, chatID, fromMessageID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.MessageID, int32, int32) error); ok {
		r1 = returnFunc(ctx, chatID, fromMessageID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FacadeService_GetChatHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatHistory'
type FacadeService_GetChatHistory_Call struct {
	*mock.Call
}

// GetChatHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - fromMessageID domain.MessageID
//   - offset int32
//   - limit int32
func (_e *FacadeService_Expecter) GetChatHistory(ctx interface{}, chatID interface{}, fromMessageID interface{}, offset interface{}, limit interface{}) *FacadeService_GetChatHistory_Call {
	return &FacadeService_GetChatHistory_Call{Call: _e.mock.On("GetChatHistory", ctx, chatID, fromMessageID, offset, limit)}
}

func (_c *FacadeService_GetChatHistory_Call) Run(run func(ctx context.Context, chatID domain.ChatID, fromMessageID domain.MessageID, offset int32, limit int32)) *FacadeService_GetChatHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		var arg4 int32
		if args[4] != nil {
			arg4 = args[4].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *FacadeService_GetChatHistory_Call) Return(messages []*domain.Message, err error) *FacadeService_GetChatHistory_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *FacadeService_GetChatHistory_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, fromMessageID domain.MessageID, offset int32, limit int32) ([]*domain.Message, error)) *FacadeService_GetChatHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessage provides a mock function for the type FacadeService
func (_mock *FacadeService) GetMessage(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) (*domain.Message, error) {
	ret := _mock.Called(ctx, chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 *domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID) (*domain.Message, error)); ok {
		return returnFunc(ctx, chatID, messageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID) *domain.Message); ok {
		r0 = returnFunc(ctx, chatID, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.MessageID) error); ok {
		r1 = returnFunc(ctx, chatID, messageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FacadeService_GetMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessage'
type FacadeService_GetMessage_Call struct {
	*mock.Call
}

// GetMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageID domain.MessageID
func (_e *FacadeService_Expecter) GetMessage(ctx interface{}, chatID interface{}, messageID interface{}) *FacadeService_GetMessage_Call {
	return &FacadeService_GetMessage_Call{Call: _e.mock.On("GetMessage", ctx, chatID, messageID)}
}

func (_c *FacadeService_GetMessage_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID)) *FacadeService_GetMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FacadeService_GetMessage_Call) Return(message *domain.Message, err error) *FacadeService_GetMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *FacadeService_GetMessage_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) (*domain.Message, error)) *FacadeService_GetMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageLink provides a mock function for the type FacadeService
func (_mock *FacadeService) GetMessageLink(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) (string, error) {
	ret := _mock.Called(ctx, chatID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageLink")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID) (string, error)); ok {
		return returnFunc(ctx, chatID, messageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID) string); ok {
		r0 = returnFunc(ctx, chatID, messageID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, domain.MessageID) error); ok {
		r1 = returnFunc(ctx, chatID, messageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FacadeService_GetMessageLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageLink'
type FacadeService_GetMessageLink_Call struct {
	*mock.Call
}

// GetMessageLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageID domain.MessageID
func (_e *FacadeService_Expecter) GetMessageLink(ctx interface{}, chatID interface{}, messageID interface{}) *FacadeService_GetMessageLink_Call {
	return &FacadeService_GetMessageLink_Call{Call: _e.mock.On("GetMessageLink", ctx, chatID, messageID)}
}

func (_c *FacadeService_GetMessageLink_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID)) *FacadeService_GetMessageLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FacadeService_GetMessageLink_Call) Return(s string, err error) *FacadeService_GetMessageLink_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *FacadeService_GetMessageLink_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID) (string, error)) *FacadeService_GetMessageLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageLinkInfo provides a mock function for the type FacadeService
func (_mock *FacadeService) GetMessageLinkInfo(ctx context.Context, link string) (*domain.MessageLinkInfo, error) {
	ret := _mock.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageLinkInfo")
	}

	var r0 *domain.MessageLinkInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.MessageLinkInfo, error)); ok {
		return returnFunc(ctx, link)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.MessageLinkInfo); ok {
		r0 = returnFunc(ctx, link)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MessageLinkInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, link)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FacadeService_GetMessageLinkInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageLinkInfo'
type FacadeService_GetMessageLinkInfo_Call struct {
	*mock.Call
}

// GetMessageLinkInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - link string
func (_e *FacadeService_Expecter) GetMessageLinkInfo(ctx interface{}, link interface{}) *FacadeService_GetMessageLinkInfo_Call {
	return &FacadeService_GetMessageLinkInfo_Call{Call: _e.mock.On("GetMessageLinkInfo", ctx, link)}
}

func (_c *FacadeService_GetMessageLinkInfo_Call) Run(run func(ctx context.Context, link string)) *FacadeService_GetMessageLinkInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FacadeService_GetMessageLinkInfo_Call) Return(messageLinkInfo *domain.MessageLinkInfo, err error) *FacadeService_GetMessageLinkInfo_Call {
	_c.Call.Return(messageLinkInfo, err)
	return _c
}

func (_c *FacadeService_GetMessageLinkInfo_Call) RunAndReturn(run func(ctx context.Context, link string) (*domain.MessageLinkInfo, error)) *FacadeService_GetMessageLinkInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type FacadeService
func (_mock *FacadeService) GetMessages(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID) ([]*domain.Message, error) {
	ret := _mock.Called(ctx, chatID, messageIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []*domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, []domain.MessageID) ([]*domain.Message, error)); ok {
		return returnFunc(ctx, chatID, messageIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, []domain.MessageID) []*domain.Message); ok {
		r0 = returnFunc(ctx, chatID, messageIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ChatID, []domain.MessageID) error); ok {
		r1 = returnFunc(ctx, chatID, messageIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FacadeService_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type FacadeService_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageIDs []domain.MessageID
func (_e *FacadeService_Expecter) GetMessages(ctx interface{}, chatID interface{}, messageIDs interface{}) *FacadeService_GetMessages_Call {
	return &FacadeService_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx, chatID, messageIDs)}
}

func (_c *FacadeService_GetMessages_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID)) *FacadeService_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 []domain.MessageID
		if args[2] != nil {
			arg2 = args[2].([]domain.MessageID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FacadeService_GetMessages_Call) Return(messages []*domain.Message, err error) *FacadeService_GetMessages_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *FacadeService_GetMessages_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageIDs []domain.MessageID) ([]*domain.Message, error)) *FacadeService_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type FacadeService
func (_mock *FacadeService) SendMessage(ctx context.Context, chatID domain.ChatID, text string) error {
	ret := _mock.Called(ctx, chatID, text)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, string) error); ok {
		r0 = returnFunc(ctx, chatID, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FacadeService_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type FacadeService_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - text string
func (_e *FacadeService_Expecter) SendMessage(ctx interface{}, chatID interface{}, text interface{}) *FacadeService_SendMessage_Call {
	return &FacadeService_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, chatID, text)}
}

func (_c *FacadeService_SendMessage_Call) Run(run func(ctx context.Context, chatID domain.ChatID, text string)) *FacadeService_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FacadeService_SendMessage_Call) Return(err error) *FacadeService_SendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FacadeService_SendMessage_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, text string) error) *FacadeService_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessageAlbum provides a mock function for the type FacadeService
func (_mock *FacadeService) SendMessageAlbum(ctx context.Context, chatID domain.ChatID, items []domain.AlbumItem) error {
	ret := _mock.Called(ctx, chatID, items)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageAlbum")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, []domain.AlbumItem) error); ok {
		r0 = returnFunc(ctx, chatID, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FacadeService_SendMessageAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageAlbum'
type FacadeService_SendMessageAlbum_Call struct {
	*mock.Call
}

// SendMessageAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - items []domain.AlbumItem
func (_e *FacadeService_Expecter) SendMessageAlbum(ctx interface{}, chatID interface{}, items interface{}) *FacadeService_SendMessageAlbum_Call {
	return &FacadeService_SendMessageAlbum_Call{Call: _e.mock.On("SendMessageAlbum", ctx, chatID, items)}
}

func (_c *FacadeService_SendMessageAlbum_Call) Run(run func(ctx context.Context, chatID domain.ChatID, items []domain.AlbumItem)) *FacadeService_SendMessageAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 []domain.AlbumItem
		if args[2] != nil {
			arg2 = args[2].([]domain.AlbumItem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FacadeService_SendMessageAlbum_Call) Return(err error) *FacadeService_SendMessageAlbum_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FacadeService_SendMessageAlbum_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, items []domain.AlbumItem) error) *FacadeService_SendMessageAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMessage provides a mock function for the type FacadeService
func (_mock *FacadeService) UpdateMessage(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, text string) error {
	ret := _mock.Called(ctx, chatID, messageID, text)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChatID, domain.MessageID, string) error); ok {
		r0 = returnFunc(ctx, chatID, messageID, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FacadeService_UpdateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMessage'
type FacadeService_UpdateMessage_Call struct {
	*mock.Call
}

// UpdateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID domain.ChatID
//   - messageID domain.MessageID
//   - text string
func (_e *FacadeService_Expecter) UpdateMessage(ctx interface{}, chatID interface{}, messageID interface{}, text interface{}) *FacadeService_UpdateMessage_Call {
	return &FacadeService_UpdateMessage_Call{Call: _e.mock.On("UpdateMessage", ctx, chatID, messageID, text)}
}

func (_c *FacadeService_UpdateMessage_Call) Run(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, text string)) *FacadeService_UpdateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChatID
		if args[1] != nil {
			arg1 = args[1].(domain.ChatID)
		}
		var arg2 domain.MessageID
		if args[2] != nil {
			arg2 = args[2].(domain.MessageID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FacadeService_UpdateMessage_Call) Return(err error) *FacadeService_UpdateMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FacadeService_UpdateMessage_Call) RunAndReturn(run func(ctx context.Context, chatID domain.ChatID, messageID domain.MessageID, text string) error) *FacadeService_UpdateMessage_Call {
	_c.Call.Return(run)
	return _c
}
